### ISSUE TITLE
Implement SPDX license expressions

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#13]
From #4:

> For me, a big part of what makes SPDX attractive is that it supports license expressions, like `MIT OR Apache-2.0`, so I think it would be nice to support those here if we can. Implementing the expression language in Dhall might not be the best idea, but would using Text and then validating the license expressions in the curator work?

For context, [here's the full documentation on license expressions](https://spdx.org/ids-how).

While having a `Text` there and validating it in CI seems like a good option, it doesn't really provide feedback to authors on the correctness of their license expression until they push here.

It looks like the full grammar of the expressions is pretty small, so I think implementing it in pure Dhall (with a similar approach as [the JSON type](https://github.com/dhall-lang/dhall-lang/blob/master/Prelude/JSON/Type)) would be quite approachable and possibly easy to use for authors, while at the same time guaranteeing correctness

**Comment by hdgarrood** [comment]
I feel like that could be a bit awkward to write in Dhall, actually; the JSON type you've linked definitely looks awkward to me, I would rather write normal JSON. Why not let registry clients perform a validation before submitting (in addition to the curator validation) if the goal is faster feedback? This already exists in the `Cabal` library so it's dead simple to implement in Haskell; the compiler does it during `purs publish`.

**Comment by f-f** [comment]
Fixed in #76
