### ISSUE TITLE
Only accept packages from GitHub?

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#15]
The `Repo` type currently in `master` can support GitHub or a generic git link:

https://github.com/purescript/registry/blob/e90a200ddcd2216258ec78145014f0fad5c5a6eb/v1/Repo.dhall#L1-L11

..but there was a concern expressed in #4 about the fact that maybe we should accept only packages from `GitHub` for now:

> Right now Pursuit only supports packages hosted on GitHub, and nobody has complained (not on the issue tracker or in any other way I might have seen, at least). The reasons for this are that allows us to use the GitHub API to get a rendered HTML readme (although I now consider that a misfeature and I'd like to remove it), and also it allows us to construct source links, since the source links take you to GitHub. If we allow non-GH packages in the registry, this means we won't be able to upload those packages to Pursuit right now (which is not a dealbreaker but probably worth considering). I'd quite like to have package sources hosted in the same place as the HTML API docs for source links though, which will probably be easier to do now with our shiny new registry; if we did that we'd be able to allow non-GH packages without losing source links.

**Comment by hdgarrood** [comment]
There is now interest in this: https://github.com/purescript/purescript/issues/3917

**Comment by f-f** [comment]
Yeah, as of #76 we still support a "generic git thing", which I think it's very important to avoid tying too much to GitHub, and as a substrate to introduce other providers more explicitly.

@hdgarrood how would you like to move on this? I think we can close it here and probably open more actionable tickets in the Pursuit repo?

**Comment by hdgarrood** [comment]
Yes, that sounds good to me.

**Comment by f-f** [comment]
https://github.com/purescript/pursuit/issues/422
