### ISSUE TITLE
Fixed record of `targets` vs a `Map` of them

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#17]
Right now, a `Package` can have a `Map` of `Target`s:

https://github.com/purescript/registry/blob/e90a200ddcd2216258ec78145014f0fad5c5a6eb/v1/Package.dhall#L24-L25

This means that in practice users will have a record with arbitrary keys, and call `toMap` on it.

An alternative design could be to fix the target names and just have the record there instead, so we'd have `targets : Targets`, where `Targets` is defined as follows:
```dhall
{ lib : Target
, app : Optional Target
, test : Optional Target
, bench : Optional Target
-- ..and so on, for all the targets we want to include
}
```

The current design is nice as the users are free to come up with all the targets they need. However, some things would get much easier with the alternative design mentioned above:
- enforcing the existence of a `lib` target - with the current design we have to run a check in CI, with the alternative the typechecker enforces it
- overriding something inside a target (useful e.g. for Trustees, see #14) - right now it would require copying the whole `targets` section (because there's no way to override values in a `Map`, so one has to copy all of it and change the things they don't like.
  Example of changing a dependency for the latest version of `aff` (see [here](https://github.com/purescript/registry/blob/master/packages/aff/v5.1.2.dhall)).
  Current approach:
  ```dhall
  https://raw.githubusercontent.com/purescript/registry/master/packages/aff/v5.1.2.dhall
  with targets =
        toMap
          { lib = Registry.Target::{
            , sources = [ "src/**/*.purs" ]
            , dependencies =
                toMap
                  { exceptions = "^4.0.0"
                  , effect = "^3.0.0"
                  , unsafe-coerce = "^4.0.0"
                  , transformers = "^4.0.0"
                  , parallel = "^4.0.0"
                  , datetime = "^4.0.0"
                  , functions = "^4.0.0"
                  }
            }
          , test = Registry.Target::{
            , sources = [ "src/**/*.purs", "test/**/*.purs" ]
            , dependencies =
                toMap
                  { free = "^5.0.0"
                  , console = "^4.1.0"
                  , minibench = "^2.0.0"
                  , assert = "^4.0.0"
                  , partial = "^2.0.0"
                  }
            }
          }
  ```
  Makes it kind of hard to spot the updated dependency..
  With the alternative instead:
  ```dhall
  https://raw.githubusercontent.com/purescript/registry/master/packages/aff/v5.1.2.dhall
  with targets.lib.dependencies =
               toMap
                  { exceptions = "^4.0.0"
                  , effect = "^3.0.0"
                  , unsafe-coerce = "^4.0.0"
                  , transformers = "^4.0.0"
                  , parallel = "^4.0.0"
                  , datetime = "^4.0.0"
                  , functions = "^4.0.0"
                  }
  ```
  It's still hard - `effect` was updated to `3.0.0` - so I guess the right solution would be to have a Dhall operator to update things in a `Map`, but now it's clear that we're only updating the dependencies of the `lib` target.

**Comment by f-f** [comment]
Update: I opened an issue in Dhall to see if it's viable to add a `Map/update` function, see https://github.com/dhall-lang/dhall-lang/issues/979

If that's possible then we'd be very fine with the current design for this with no need to consider using a record.

**Comment by Gabriella439** [comment]
@f-f: What about parametrizing the `Target` type on the record of dependencies so that you could actually store a bona-fide record inside:

```dhall
let Target =
      λ(dependencies : Type) → { source : List Text, dependencies : dependencies }

let Package =
      λ(args : { lib : Type, app : Type, test : Type, bench : Type }) →
        { lib : Target args.lib
        , app = Target args.app
        , test = Target args.test
        , bench = Target args.bench
        }
```

Then if you had that, you could write what you originally wanted:

```dhall
somePackage
  with targets.lib.dependencies.effect = "^3.0.0"
```

**Comment by f-f** [comment]
@Gabriel439 interesting suggestion, thanks!

Though I guess this would mean that package authors will have to specify the type of the dependency record for every target, which doesn't sound appealing at all...e.g. this would mean editing both the record type and the record implementation when adding a dependency.
E.g. [take a look at an example manifest](https://github.com/purescript/registry/blob/master/packages/aff/v5.1.2.dhall) - the author would have to specify two dependency records there, which I find kind of verbose.

One of the goals of this design is that people would encounter a similar amount of affordance wrt having the same configuration in JSON/YAML, but with the added benefits that Dhall brings in: security features, imports, typechecking.
For comparison, [this is the same manifest I linked above](https://github.com/purescript-contrib/purescript-aff/blob/v5.1.2/bower.json), but in its current JSON incarnation.

I think the Dhall and the JSON versions are comparable right now, and I would like to keep them to a comparable size.

Another issue that I foresee with parametrizing `Package`/`Target` is that automatically reading a package manifest from Haskell might not be straightforward?

**Comment by f-f** [comment]
I guess the "proper proper" solution for this would be Row Types in Dhall, but that would require some type inference to have a nice UX..

**Comment by Profpatsch** [comment]
Is there any specific reason you need to use `//` for overrides? What speaks against using an interpretation layer that specifies the override semantics without being a subset of the dhall semantics?

That is have a function `override` in your library that takes a `Map` and an `Override` and returns a new `Override`.

```
let Override = { overrides = List (Map Text Version) }
let override = \(map: Map Text Version) -> \(override: Override) -> { overrides = override.overrides # [ map ] }
```

and do the “real” overriding in your interpretation layer.
If you intepret in nix you can even make it an opaque type:

```
\(Override : Type) ->
\(override : ∀(map: Map Text Version -> ∀(override: Override) -> Override) ->
…
```

And pass the actual function from the outside of your config alltogether.

**Comment by Gabriella439** [comment]
@Profpatsch: Generally, we try to avoid pushing custom code into the interpreter if it is avoidable, and in this case it seems like other use cases are hitting the same issue, so the solution should probably be upstreamed into the language

For more details, see the discussion on: https://github.com/dhall-lang/dhall-lang/issues/979

**Comment by f-f** [comment]
@Profpatsch 1.5 years of running Spago taught me that I should really not mess with interpreting Dhall in a custom way, because then we get things like https://github.com/purescript/spago/issues/594 (which you reported, so you probably feel this problem at least as much as I do)

So this time around I'd really like to keep things as vanilla as I can. I reported this upstream because it's a usecase we have since years in PureScript land, and that I saw popping up in multiple other places, as Gabriel mentioned above.

**Comment by Profpatsch** [comment]
For reference I’m not talking “interpreting” as in “adding new symbols to the language” or “parsing the AST in a custom way” here.

The examples I gave are still valid upstream dhall sources that can be typechecked and called from other dhall code (as opposed to what spago does with maps for example).

**Comment by f-f** [comment]
I'll go ahead and close this since #76 moves the Manifest to JSON, and all Dhall concerns should be handled in Spago instead (for the record I still think the `fromMap` operator will be necessary for good UX, but this is tracked anyways in https://github.com/dhall-lang/dhall-lang/issues/979)
