### ISSUE TITLE
Suggestion: use `dhall format`

### ISSUE THREAD

**Issue by toastal** [purescript/registry-dev#171]
Dhall is requirement to the registry and it ships with a first-party formatter. It would seem better if everyone were encouraged to use it for style consistency—this project should be using `dhall format` as well.

**Comment by f-f** [comment]
Dhall is not a requirement for users to interact with the registry - package authors will only have deal with JSON, for package manifests and publishing operations.
We use Dhall only on the CI side and for specifying types, that are fairly commented for documentation purposes - `dhall format` removes all these comments. [There are efforts to fix that](https://github.com/dhall-lang/dhall-haskell/pull/2173) but until then we are not interested in autoformatting the repo.
