### ISSUE TITLE
Renaming a package from the `bower-packages.json`

### ISSUE THREAD

**Issue by paluh** [purescript/registry-dev#175]
Thanks a lot for your work on the _purescript/registry_!

I have this quite unusual scenario - I want to rename / deprecate a package which is listed in `bower-packages.json` (specifically _polyform-validators_ into _polyform-batteries-core_ - it was renamed long time ago but not in the bower registry itself).
I can also add this as a new package and deprecate the other one. The problem is that I need to change the existing (validators) lib url in such a case so the deprecated package links to a stub repo with deprecation warning. Could you please suggest me how to approach?

**Comment by f-f** [comment]
Hi @paluh! We don't rename packages, but if you own all the packages involved then we can do as you proposed:
- point the deprecated package to another URL
- then you can register another name for the new package

**Comment by paluh** [comment]
Hi @f-f!

Thanks for the quick response.

Could you please tell me if my plan is correct:

* I should make a proper release of _polyform-validators_ under a new URL (like https://github.com/lambdaterms/purescript-polyform-validators) which contains only a README.md with deprecation warning.
* I should provide a PR to the _registry_ which updates `bower-packages.json` and changes the repo address to the new one.
* I should provide a PR with a new package which points to the old URL. I want to use current _polyform-validators_ URL for the new package _poyform-batteries-core_ - is it a problem?

**Comment by f-f** [comment]
@paluh this is all fine by our policies (mainly "only maintainers can change their package urls" and "we don't remove names from the registry"), but it might be breaking for the users of the library, so make sure to cut major releases

cc @thomashoneyman for input on this

**Comment by thomashoneyman** [comment]
This sounds fine to me!

**Comment by paluh** [comment]
I'm closing this as this scenario was already merged in #178 . Thanks a lot for your support Guys!

**Comment by f-f** [comment]
You're welcome!
