### ISSUE TITLE
Reassign uint, float32, arraybuffer

### ISSUE THREAD

**Issue by jamesdbrock** [purescript/registry-dev#182]
I would like to reassign soon (not quite yet)

* __zaquest/purescript-uint → purescript-contrib/purescript-uint__
* __athanclark/purescript-float32 → purescript-contrib/purescript-float32__
* __jacereda/purescript-arraybuffer → purescript-contrib/purescript-arraybuffer__

Discussion in https://github.com/purescript-contrib/governance/issues/40

**Comment by jamesdbrock** [comment]
@zaquest @athanclark @jacereda

**Comment by jacereda** [comment]
https://github.com/purescript-contrib/purescript-arraybuffer

**Comment by jacereda** [comment]
I transferred before noticing https://github.com/purescript-contrib/purescript-arraybuffer/issues/29

Also, https://github.com/purescript/registry/actions/runs/952064696/workflow

**Comment by jamesdbrock** [comment]
> I transferred before noticing [purescript-contrib/purescript-arraybuffer#29](https://github.com/purescript-contrib/purescript-arraybuffer/issues/29)
> 
> Also, https://github.com/purescript/registry/actions/runs/952064696/workflow

That's fine, we can work with this.

**Comment by f-f** [comment]
Fixed in #184
