### ISSUE TITLE
Root JSON diffs always contain trailing comma issues

### ISSUE THREAD

**Issue by toastal** [purescript/registry-dev#205]
All of the diffs in pull requests for additions contain extra lines which just makes the history uglier. Some commits, like [this](https://github.com/purescript/registry/pull/193/commits/8cc95f926cfb58be23125688e7c1876c03a2aa89), exist just to deal with the commas. JSON5 supports trailing commas (and comments) or the JSON could be comma-first style which would eliminate this issue.

**Comment by f-f** [comment]
@toastal these JSON files are temporary until we ship the live version of the registry. I appreciate the suggestion, but I am not sure it's worth spending time optimizing the workflow to deal with these

**Comment by toastal** [comment]
Ohh... I thought this was more long-term. Closing.
