### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by toastal** [purescript/registry-dev#206]
I'm sure we already know [EditorConfig](https://editorconfig.org/). Halogen has [one](https://github.com/purescript-halogen/purescript-halogen/blob/master/.editorconfig) as do many other projects and it would help with consistency. My editor was giving me 8-spaced tabs (default in Vims) without having this file.

**Comment by thomashoneyman** [comment]
I'd be happy with a PR adding an editorconfig. Here's the standard one used in PureScript Contributors:

https://github.com/purescript-contrib/governance/blob/main/updater/templates/base/.editorconfig
