### ISSUE TITLE
Write tests for the Registry.Index module

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#212]
The [`Registry.Index` module](https://github.com/purescript/registry/blob/master/ci/src/Registry/Index.purs) supports reading and writing to the registry index. (For context, the registry index is a listing of all packages in the registry along with their manifest files.) This code has not yet been tested, and we need to make sure that once run it does produce a valid registry index which can be read.

**Comment by thomashoneyman** [comment]
One possible approach to implement these tests:

1. Read an existing registry index
2. Insert an item into the registry index
3. Verify the resulting registry index is correct

We could, for example:

1. Read a fixture file for the initial index, kept in the `fixtures` directory
2. Insert an item and write the result to a temporary file
3. Read the result again and check that the written item is there
4. Delete the temporary file

**Comment by thomashoneyman** [comment]
cc: @colinwahl -- does that proposed testing plan seem reasonable to you?

**Comment by colinwahl** [comment]
Yeah, that seems reasonable to me!

**Comment by f-f** [comment]
I thought this was about verifying that the generated directory structure is correct?

**Comment by thomashoneyman** [comment]
We could also just verify that, by hand, if we’d rather not have automated tests. In general none of the functions in the module have been tested yet so it would also be good to make sure the JSON lines format is working for writing and reading as well, and that writing a new file works too.

**Comment by colinwahl** [comment]
@thomashoneyman and I got something mostly working for this last week - I just wanted to see if I could package it up into `purescript-spec` rather than throwing errors in `Aff`. I'll try to get it cleaned up soon!
