### ISSUE TITLE
Produce a graph of package versions and their dependencies from the registry index

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#214]
The registry contains a registry index, which is a list of all packages in the registry along with their manifests (which themselves include information about dependencies, licenses, and so on):

https://github.com/purescript/registry/blob/3f5c48e518f657ab03c4178df976648c9fb1437f/ci/src/Registry/Index.purs#L24

In order to upload a new registry index as part of our pipeline, we need to be able to order packages at specific versions by their dependencies, so that we only upload packages that already have all their dependencies present (at correct versions) in the registry. That way the registry index is always correct.

I'm proposing we implement a function:

```purs
toVersionsGraph :: RegistryIndex -> PackageVersionsGraph
```

where a `PackageVersionsGraph` contains every package version in the registry, and we can order it topologically:

```purs
toOrderedArray :: PackageVersionsGraph -> Array Manifest
```

...so as to walk through each package version in order and upload it to the registry index.

**Comment by thomashoneyman** [comment]
I've assigned this to you, @f-f, since you said you had some code locally for it. If I'm misremembering then please let me know and I will unassign it!

**Comment by f-f** [comment]
This is all right thanks, I will sort out the code that I have locally and push up a PR!

**Comment by colinwahl** [comment]
I've made good progress on this on my branch `package-version-graph` - I am hoping to have a PR up soon, just finishing up some last cleanup.
