### ISSUE TITLE
Kickoff the API pipeline in batch mode for Bower packages

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#215]
Once we produce a graph in #214 we should be able to take these packages in topological order and then uploads them one after the other, running locally and using the current `Registry.API` code.

**Comment by f-f** [comment]
As of #288 we are now able to successfully import all the core packages, but I'll leave this open until we have a PR that adds all the Metadata files here.

**Comment by thomashoneyman** [comment]
> until we have a PR that adds all the Metadata files here.

Do you mind clarifying this? I'm not sure what this is referencing.

**Comment by f-f** [comment]
If you run the legacy-import script locally, it will:
1. Upload all the packages
2. Update a local copy of the `registry-index` repo with the new info
3. Update a metadata file for each package, where we store the hashes and stuff. These files are our source of truth! I.e. if a package version is there THEN it's in the registry and (should be) available for download.

What I'm referencing above is the product of step 3, which is a bunch of files in the `metadata` folder, which right now we don't have since no package has been uploaded yet 🙂 
(Well, a bunch of tarballs are on DO, but we should nuke them until we commit the metadata here. However that's not done yet because things are in flux and running the import takes a long while)

**Comment by thomashoneyman** [comment]
This has been done, and we’ll continue to run uploads regularly (#425), so I’m going to close this.
