### ISSUE TITLE
Consider lower-casing package names imported from Bower

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#217]
The Bower import script currently excludes only one package for having a malformed package name:

```json
  "malformedPackageName": {
    "TypeAhead": {
      "v0.1.0": "Package name should start with a lower case char or a digit; pos = 0",
    }
  }
```

However, this _would_ be a valid package name if it were all lower-cased. This issue tracks discussion on whether we should fix this package name or exclude it from the registry -- and, in general, if we should process package names to lower-case them prior to parsing them as `PackageName`s.

**Comment by f-f** [comment]
I think we should do this if all the new names would not introduce clashes - i.e. it would be an issue if we'd have different packages called `TypeAhead` and `typeahead`

**Comment by thomashoneyman** [comment]
Yep. There is only one package affected by this casing restriction, and there are two packages sharing the same name:

https://github.com/purescript/registry/blob/daf1399c458b8159deb473358a707c660af2fc27/bower-packages.json#L2
https://github.com/purescript/registry/blob/daf1399c458b8159deb473358a707c660af2fc27/bower-packages.json#L1308

...so I'm going to close this issue.

**Comment by f-f** [comment]
I think we should consider doing this, because packages with uppercase characters are going to be rejected anyways by our current pipeline checks, see how we parse `PackageName`s:
https://github.com/purescript/registry/blob/daf1399c458b8159deb473358a707c660af2fc27/ci/src/Registry/PackageName.purs#L46

**Comment by thomashoneyman** [comment]
That's true, but only one package actually fails with a `MalformedPackageName` error -- and we can't even fix that package, because it has a name conflict with another package.

For that reason I don't see it being worth the time to implement a processing step to lower-case package names before importing them from the Bower registry: it wouldn't fix any packages, and we'd have to put in a separate check for name clashes that we don't have now.

**Comment by f-f** [comment]
Oh yes, I see now! So I think here we are proposing that:
- we lowercase package names (we have to)
- we drop `purescript-TypeAhead` because it clashes

Is this accurate?

**Comment by thomashoneyman** [comment]
Originally, yes, that was the proposal. But my proposal now is:

* We don’t lower-case names; we just verify they are already lower-cased when we parse them
* We drop TypeAhead as a MalformedPackageName (which already happens, because it fails to parse)

And with that proposal we can close this ticket because we already do these

**Comment by f-f** [comment]
Wonderful, thanks you for clarifying! I'll close this then
