### ISSUE TITLE
Trim JS dependencies out of imported Bowerfiles

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#219]
Some packages cannot be imported to the new registry from the old registry because they contain dependencies that are not in the registry. However, sometimes these dependencies are not in our registry list because they are _JavaScript_ dependencies. Ordinarily we don't consider JS dependencies; for example, the `purescript-react` package doesn't depend on `react` even though it _does_ require it to work.

There are packages that would be valid if they did not declare any JS dependencies in their Bowerfiles. Since we don't care about their JS dependencies anyways, I'm proposing that we strip out non-PureScript dependencies from packages being added to the registry.

One example is `purescript-ace`, which fails because it depends on `ace-builds` (a JS package):

https://github.com/purescript-contrib/purescript-ace/blob/38cd31854d779ce565dd43f138aeda588ec71d4c/bower.json#L30-L31

It's a shame to remove `ace` from the registry altogether (it's used by various PureScript applications) since it declares this dependency, given that it would work if we just dropped the JS dependency from the package.

To fix this issue, we could:

* Process Bowerfiles after they have been imported to strip out packages that do not have a `purescript-` prefix.
* Or, attempt to keep the Bowerfile as-is, and only strip out packages without `purescript-` prefixes if the Bowerfile is found to contain non-registry dependencies.

I _believe_ it's safe to use a heuristic of the `purescript-` prefix for PureScript packages in the Bower registry, but I may be mistaken. In that case, then we can close this issue.

**Comment by thomashoneyman** [comment]
In fact, I think we _have_ to do this. For example, this is a perfectly valid Bowerfile according to the pipeline:

https://github.com/joneshf/purescript-c3/blob/master/bower.json

```json
{
  "name": "purescript-c3",
  "version": "0.1.1",
  "description": "PureScript bindings for c3.",
  "license": "MIT",
  "dependencies": {
    "c3": "~0.2.4",
    "d3": "~3.4.8",
    "purescript-dom": "~0.1.0"
  }
}
```

All dependencies are considered to be valid package names. All dependencies are in the PureScript registry, because there _is_ a `purescript-c3` (it's this very package) and there _is_ a `purescript-d3`. The result is a valid `Manifest`, even though both the `c3` and `d3` dependencies referenced here are actually _JavaScript_ dependencies. Here's the resulting manifest file:

```json
{
  "name": "c3",
  "license": "MIT",
  "version": "0.1.1",
  "repository": {
    "githubOwner": "joneshf",
    "githubRepo": "purescript-c3"
  },
  "targets": {
    "lib": {
      "sources": [
        "src/**/*.purs"
      ],
      "dependencies": {
        "dom": ">=0.1.0 <0.2.0-0",
        "d3": ">=3.4.8 <3.5.0-0",
        "c3": ">=0.2.4 <0.3.0-0"
      }
    }
  }
}
```

Instead, we should only produce a manifest referencing the `dom` package, since it's the only PureScript dependency.

**Comment by f-f** [comment]
Wow, this is a great catch!
