### ISSUE TITLE
Parse LICENSE file if no license is listed in the Bowerfile

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#220]
Some packages do not declare a `license` field in their Bowerfiles, despite having a valid SPDX license in the repository root. One example is `aff-coroutines` at its initial released version:

https://github.com/purescript-contrib/purescript-aff-coroutines/tree/v0.1.0

If we don't find a license in the imported Bowerfile (or in the imported `spago.dhall` file if / when #218 is implemented), but there is a `LICENSE` file in the repository root, then we should try to parse that and use it as the package's license in the produced `Manifest`.

**Comment by thomashoneyman** [comment]
This will only work if we can find a suitable library for parsing LICENSE files. Absent that, we should close this issue, because we're certainly not going to expend the effort to write one ourselves!

**Comment by thomashoneyman** [comment]
One potential option is:
https://github.com/juancarlospaco/parselicense

**Comment by YanikCeulemans** [comment]
Looking at the source code for the "parselicense" repo it appears that it actually just runs MD5 on the license content and compares it to a static set of known MD5 hashes. It would be trivial to port it to purescript, i.e. something like the pseudocode `String.trim >>> String.toLowerCase >>> hashWithMD5`.

The downside would be that the known set of MD5 hashes has to be maintained.

**Comment by YanikCeulemans** [comment]
Searching npm, I didn't get a lot of results for a parser for license contents. Most of them just deal with the spdx expression. The few that actually use the license file contents use a regex that matches the start of the license, hardly a sound check.

**Comment by f-f** [comment]
@YanikCeulemans thanks for looking into this! I think an easy approach to this would be:
- implement that MD5 check
- fetch all the licenses that we have to parse, and collect them into bins based on their MD5
- map every bin to its SPDX type
- maintain a set of MD5s here starting from these bins

I think it's acceptable to maintain the list of hashes here, because this import is sort of temporary - hopefully we'll have to run it only a couple of times, and then we can switch over to using the pipeline for new packages.

**Comment by maxdeviant** [comment]
Maybe I'm missing something, but how would we be able to get a consistent MD5 hash across license files if there are variable parts of the license (like the copyright holder's name)?

**Comment by maxdeviant** [comment]
> Maybe I'm missing something, but how would we be able to get a consistent MD5 hash across license files if there are variable parts of the license (like the copyright holder's name)?

This was more a question about the implementation of the aforementioned `parselicense`, because from the implementation I can't tell how it gets consistent hashes.

But from reading through @f-f's comment (https://github.com/purescript/registry/issues/220#issuecomment-920460262), it sounds like we would be hashing each individual package's license file, storing the hashes, and then (by hand?) sorting them into buckets with the correct SPDX type?

**Comment by maxdeviant** [comment]
I took a first pass at resolving licenses from the `package.json` (if one is present). We'll probably need to do this in conjunction with parsing the LICENSE file, as I noticed some Bower packages had a `license` specified in the `package.json`, but no LICENSE file in the repo.

I have to clean a few more things up, but I should have a PR up in the next day or so 😄

**Comment by thomashoneyman** [comment]
> I took a first pass at resolving licenses from the `package.json` (if one is present). We'll probably need to do this in conjunction with parsing the LICENSE file, as I noticed some Bower packages had a `license` specified in the `package.json`, but no LICENSE file in the repo.

@maxdeviant Perhaps we can talk more about this in #218? That ticket may need to be broadened out to cover multi-stage fallbacks when there aren't Bowerfiles. I'll add a little more detail over there.

**Comment by thomashoneyman** [comment]
@maxdeviant I've actually created #233 as a better place to discuss that.

**Comment by thomashoneyman** [comment]
Another tool we could rely on is this one:
https://github.com/nexB/scancode-toolkit

**Comment by thomashoneyman** [comment]
Wait! Totally forgot about GitHub's `licensee` project, and...they have an API:
https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository

The resulting `license` object includes (for example):

```json
{
    "key": "mit",
    "name": "MIT License",
    "spdx_id": "MIT",
    "url": "https://api.github.com/licenses/mit",
    "node_id": "MDc6TGljZW5zZW1pdA=="
}
```

...and we could pull out the `spdx_id` field to serve as the license if there isn't one otherwise specified!

**Comment by maxdeviant** [comment]
> Wait! Totally forgot about GitHub's `licensee` project, and...they have an API:
> https://docs.github.com/en/rest/reference/licenses#get-the-license-for-a-repository
> 
> The resulting `license` object includes (for example):
> 
> ```json
> {
>     "key": "mit",
>     "name": "MIT License",
>     "spdx_id": "MIT",
>     "url": "https://api.github.com/licenses/mit",
>     "node_id": "MDc6TGljZW5zZW1pdA=="
> }
> ```
> 
> ...and we could pull out the `spdx_id` field to serve as the license if there isn't one otherwise specified!

Nice! I was actually wondering if we could access this information somehow, cause I know that GitHub already does something like this with the license badge that they show on the repo.

**Comment by JordanMartinez** [comment]
I think using the GitHub API to get the license comes with an implicit assumption: that the user never changed the license to something else later.

Let's say I made package `foo` from versions `v1.0.0` to version `v8.0.0` and the license was `GPLv3`. Let's say I then released `v9.0.0` but changed the license to `MIT`. I'm assuming the API above would always return `MIT` because that's what the version is now. 

We should verify whether this assumption is true, but I believe it is because the API does not provide a "version" argument.

**Comment by YanikCeulemans** [comment]
I checked the react repository which used to have a BSD license in earlier versions, see: [https://github.com/facebook/react/blob/v0.14.1/LICENSE](https://github.com/facebook/react/blob/v0.14.1/LICENSE). However the Github API returns that its license is MIT. I think it's safe to assume that Jordan's assumption is correct.

```
curl \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/facebook/react/license
{
  // ... more json ....
  "license": {
    "key": "mit",
    "name": "MIT License",
    "spdx_id": "MIT",
    "url": "https://api.github.com/licenses/mit",
    "node_id": "MDc6TGljZW5zZTEz"
  }
}
```

**Comment by thomashoneyman** [comment]
In that case we can fall back to using the `licensee` tool which powers this API, which can be made available via a Nix shell for use when running the script (ie. `nix-shell -p licensee`).

https://github.com/licensee/licensee

Running that tool via the CLI identifies React 0.14.1 as BSD-3-Clause.

**Comment by YanikCeulemans** [comment]
So this means we are going to need to be able to run shell commands from within purescript (using a node child process), correct? If so, would it be preferable that the api to such a module runs in `Aff`? i.e. something along the lines of:
```purescript
spawnLicensee :: RepoPath -> Aff String
```

**Comment by thomashoneyman** [comment]
Yea, I think we can use `execSync`, which is in `Effect`:

https://github.com/purescript-node/purescript-node-child-process/blob/5c4e560eceead04efc1d5a3ec1f6de91bb1d512e/src/Node/ChildProcess.purs#L385

**Comment by f-f** [comment]
Note that we already run shell commands somewhere else in the codebase, see [here](https://github.com/purescript/registry/blob/master/ci/src/Foreign/Dhall.purs)
