### ISSUE TITLE
Print out statistics on package failures in Bower import

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#222]
The Bower import tool converts Bowerfiles for packages in the Bower registry into valid `Manifest`s. However, many packages fail along the way and are collected into a `PackageFailures` map:

https://github.com/purescript/registry/blob/3f5c48e518f657ab03c4178df976648c9fb1437f/ci/src/Registry/Scripts/BowerImport/Error.purs#L15

Later, these failures are written out to a file called `bower-exclusions.json`:
https://github.com/purescript/registry/blob/3f5c48e518f657ab03c4178df976648c9fb1437f/ci/src/Registry/Scripts/BowerImport.purs#L167-L169

However, we also would benefit from knowing some statistics about the package failures, which could be written out to a file or just printed to the console. As a first cut, we'd specifically like to know:

* How many packages succeeded in total? How many packages failed in total?
* How many package versions succeeded in total? How many package versions failed in total?
* How many incidences are there of each error (`MissingLicense`, `BadDependencyVersions`, etc.), in sorted order (ie. most failures are at the top of the list, least failures are at the bottom of the list).

These statistics can help us prioritize what issues to fix and report on how many packages are being omitted from the PureScript registry and for what reasons.

**Comment by ntwilson** [comment]
I'm happy to take a first stab at this!
