### ISSUE TITLE
Reintroduce `Address` type for package sets

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#245]
An earlier revision of the registry spec included an `Address` type that described where you could find the sources for a particular package:

https://github.com/purescript/registry/blob/14a8fb7c6c711ae2bcee54c4753010d57af11721/v1/Address.dhall

```dhall
let Address = 
  < Registry : { name : Text, version : Text }
  | Repo : Repo
  | Local : Prelude.Location.Type 
  >
```

It could be used to override a package in the package set (or add new ones to the package set), for example:

https://github.com/purescript/registry/tree/14a8fb7c6c711ae2bcee54c4753010d57af11721#overriding-a-package

However, this type was later removed, which means that a package set _always_ points to packages from the Registry. That would mean that you can create your own custom packages sets, but they would solely be comprised of packages from the registry and you just choose the packages and versions. If you wanted anything outside the registry (for example, a private package), then you're out of luck. With this model, it's up to the package managers to implement a way to use packages outside of the package set.

However, I think that it's considerably nicer to be able to create your own package set or modify the existing package set to produce the list of available dependencies for your project -- including packages outside the registry, like your own internal packages. This way the package set is always the list of available packages to install, and you don't have to learn a new way to install packages depending on whether they're in the registry or not.

To do that, I propose we:

1. Reintroduce the `Address.dhall` file / type, and use it to implement the official package set
2. Use `assert` or some other validation step to require the official package set to _only_ use packages with the `Registry` constructor (only packages in the registry are allowed in the official set)
3. Reintroduce documentation on how you can add new packages to your custom package set.

**Comment by f-f** [comment]
> Use `assert` or some other validation step to require the official package set to only use packages with the `Registry` constructor (only packages in the registry are allowed in the official set)

I originally proposed this check, and I'll clarify here what I mean with "let's use `assert` to verify things":

```dhall
-- let's assume we use the `Address` type defined above

-- then this is our "package set"
let packages =
  { prelude = Address.Registry { name = "prelude", version = "v4.1.1" }
  , effect = Address.Registry { name = "effect", version = "v2.0.0" }
  , simple-json = Address.Registry { name = "simple-json", version = "v7.0.0" }
  }

-- we then define a function that will map an element of the map to `True`
-- only if it's a `Registry` constructor
let Pkg = Prelude.Map.Entry Text Address
let isRegistryPkg = \(pkg : Pkg) -> merge
      { Registry = \(x : { name : Text, version : Text }) -> True
      , Repo = \(x : Registry.Repo) -> False
      , Local = \(x : Prelude.Location.Type) -> False
      } pkg.mapValue

-- we can then use this function in a compile-time assertion!
-- here we map all the packages in the set with the function defined above,
-- then we say "all the elements of this list are `True`"
let test = assert :
      Prelude.List.all Bool (\(x : Bool) -> x == True)
        (Prelude.List.map Pkg Bool isRegistryPkg (toMap packages))
      ===
      True
```

If you're interested in using this more, take a look at Dhall's Prelude, where all the functions are tested using this method. E.g. [here's `List.map`](https://store.dhall-lang.org/Prelude-v21.1.0/List/map.dhall.html)

cc @colinwahl

**Comment by artemisSystem** [comment]
As briefly discussed with Thomas on discord, `Repo` should be changed to let you specify a version (perhaps a `ref` field in `CommonData`? https://github.com/purescript/registry/blob/master/v1/Repo.dhall#L14)

**Comment by f-f** [comment]
We should have a `ref` field, but it should not go in the `Repo` type, as that represents "a pointer to a repository" and not to "a specific ref in a repository".

Instead let's add it to `Address`, so we'd end up with:

```dhall
let Address = 
  < Registry : { name : Text, version : Text }
  | Repo : { repo : Repo, ref : Text }
  | Local : Prelude.Location.Type 
  >
```
