### ISSUE TITLE
Push to various repositories from the publishing pipeline

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#265]
We are supposed to push changes to several repositories when publishing a new package, and we currently don't. See https://github.com/purescript/registry/issues/213#issuecomment-961285257 for a detailed implementation plan for this.

**Comment by thomashoneyman** [comment]
Until we officially migrate the repositories to their final destinations, we can use this as the "registry" to push to:
https://github.com/purescript/registry-preview

**Comment by f-f** [comment]
Closing as implemented
