### ISSUE TITLE
Include output of `purs graph` somewhere...?

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/registry-dev#27]
Not sure whether this should go here (maybe Pursuit would be a better spot?), but I thought I'd raise it for discussion.

**Comment by f-f** [comment]
What would be the use case for this?

Also note that packages have version bounds, so we'd have to solve and fix a set of versions to include with the graph? But the the generated graph would be quite arbitrary since you could just solve with different versions and get a different graph?

**Comment by JordanMartinez** [comment]
I raised this here because I thought it might be easier to piggy-back this idea on top of the registry for two reasons. First, the registry will be a centralized place of downloads and whatnot. Second, it looks like the package sets will be integrated into this at some point. Including this info as part of the package set might be useful elsewhere. However, I'd guess that this inclusion would increase the scope of the registry beyond what it should be, and is actually a bad idea.

On further thought, including this data into Pursuit seems like a better place since it has a documentation focus. If Pursuit was upgrade to also show all packages in a given package set, then this graph data could be used to display interesting things:
- "downward focused"
    - what modules/packages do I implicitly use / depend upon?
    - a license graph (i.e. if I depend on X, on how many other licenses am I implicitly depending?)
- "upward focused"
    - who uses my module? Who or what is impacted if I make a breaking change?

**Comment by f-f** [comment]
@JordanMartinez since this would be package-sets-specific, how do you feel about addressing this in Spago?

**Comment by JordanMartinez** [comment]
We could do it in Spago. I've been working on something like this using `graphviz` and `dot`: [jordanmartinez/purescript-module-graph](https://github.com/jordanmartinez/purescript-module-graph). Then I got distracted by the cookbook work. Unfortunately, when I did render the dependency graph for the entire package set, it was so unreadable that I wasn't sure how helpful it would be. I've since changed it to show only the dependency and dependent graph for a single package.

**Comment by f-f** [comment]
@JordanMartinez I see, thanks for the update! cc @afcondon since we discussed this the other day

**Comment by afcondon** [comment]
thanks for the ping, @f-f fabrizio, this is indeed something i'm interested in... @JordanMartinez i might have some strategies for you, hit me up if you have a mo' to talk about it and i can screenshare some stuff in the picture-is-worth-1K-words dept...

**Comment by JordanMartinez** [comment]
@afcondon This is what I got so far:
![image](https://user-images.githubusercontent.com/8413037/84580455-10f8f800-ad8c-11ea-8d9c-c03a0da32a5b.png)

The general approach I was going to take was
- have client query server for graph
- server uses parsed data to write out a `.dot` file, then calls `dot` to produce an image, and then send that image back to client
- client renders the image

Yeah, I'd like to see that screenshare. Message me on Slack and let's find a time that works for both of us.
