### ISSUE TITLE
Rename `hash` in Metadata?

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#290]
Right now we just include a `hash` field in the Metadata for every package:
https://github.com/purescript/registry/blob/85503f8fc24ac8358911cd5b4c4292a9803dd0e1/v1/Metadata.dhall#L14

I was wondering: should this be clearer, and/or more future-proof? What if we want to change the hashing function at some point?

So I'd like to discuss if we should do anything about this. Some ideas:
- we could rename the `hash` field to `sha256`, so that we can add new fields without trying to reuse this one
- or we could change the type to a record like `hash: { sha256: "57ba32c54958..." }`, so that we can have a "variant" in there if we need to add new hashing functions
- or we could add information about the hashing used in the string itself, e.g. "sha256-57ba32c54958.." (does this scheme have a name? I think so but I couldn't find it)

cc @thomashoneyman @cdepillabout

**Comment by cdepillabout** [comment]
cc @ddellacosta from https://github.com/cdepillabout/purescript2nix/issues/4

> we could add information about the hashing used in the string itself, e.g. "sha256-57ba32c54958.."

This sounds like an SRI hash: 

- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
- https://www.w3.org/TR/SRI/

An example would be like `sha384-dOTZf16X8p34q2/kYyEFm0jh89uTjikhnzjeLeF0FHsEaYKb1A1cv+Lyv4Hk8vHd`.  A `sha256-` prefix is also valid.  The difference between an SRI hash and your above example is that an SRI hash is base-64-encoded.

-----------------------------------

As far as `purescript2nix` is concerned, a Nix-compatible hash is required.

For Nix, the most forward-compatible choice would likely be an SRI hash.  Currently `sha256-` seems to be most widely used (although `sha384-` and `sha512-` are also supported).  A base-16-encoded sha256 hash is also supported by Nix.  (Although I'm not actually sure what is the full set of supported hash-types in Nix.)

**Comment by f-f** [comment]
> For Nix, the most forward-compatible choice would likely be an SRI hash

Wonderful, I think we can move forward with base64 sha256 SRI hash then!

**Comment by f-f** [comment]
@cdepillabout do you know of a command to easily produce such hashes with Nix? `nix-hash` doesn't seem to support base64 :thinking:

**Comment by thomashoneyman** [comment]
I'm on board with using SRI hashes, I think that's a great idea.

**Comment by cdepillabout** [comment]
> do you know of a command to easily produce such hashes with Nix? nix-hash doesn't seem to support base64

It looks like this unfortunately changes depending on whether you are using nix-2.3 or nix-2.4.

If you're using nix-2.3, you can hash an arbitrary file and produce a sri hash with the following command:

```console
$ nix --version
nix (Nix) 2.3.16
$ nix hash-file --sri ./CHANGELOG.md
sha256-5+jMz14tP1751P7cvYvqWB9tTUaJIptrWG4ekP+IobI=
```

If you're using nix-2.4, then you need to explicitly enable the experimental `nix-command` feature:

```console
$ nix --version
nix (Nix) 2.5pre20211126_55275fc
$ nix --experimental-features "nix-command" hash-file --sri ./LICENSE 
warning: 'hash-file' is a deprecated alias for 'hash file'
sha256-qlvxRze+tm7huINpYc8Lj3tXMLOCrAgMYzirZ7xeD5I=
```

From this warning you can see that nix-2.4 has changed this command from `hash-file` to `hash file`:

```console
$ nix --version
nix (Nix) 2.5pre20211126_55275fc
$ nix --experimental-features "nix-command" hash file --sri ./LICENSE
sha256-qlvxRze+tm7huINpYc8Lj3tXMLOCrAgMYzirZ7xeD5I=
```

(Most nix users set the `nix-command` experimental features flag in their `/etc/nix/nix.conf` file.)

-------------------------------------

https://www.w3.org/TR/SRI/ also gives a way to do this with `openssl` (if you don't want to rely on Nix):

```console
$ openssl dgst -sha256 -binary < ./LICENSE | openssl base64 -A
qlvxRze+tm7huINpYc8Lj3tXMLOCrAgMYzirZ7xeD5I=
```

**Comment by f-f** [comment]
Thanks @cdepillabout!

Then I'd say our course of action here should be:
- change the hashing logic from "base16 sha256" to "base64 SRI sha256"
- add tests that verify that our hashing logic returns the same hash as
    - `nix hash-file --sri $FILE`
    -  and as `openssl dgst -sha256 -binary < $FILE | openssl base64 -A`
