### ISSUE TITLE
Only include files from 'targets' key in package tarballs

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#292]
When a package is uploaded to the registry, we take the repository and create a tarball of its contents. We then hash those contents. However, packages often contain files that are not needed when they are being distributed as dependencies -- for example, an `examples` directory containing some additional source code.

We can reduce the size of packages by only including files that are listed in the manifest's `targets` key, as well as the few files necessary for package distribution (the package manifest, for example), before creating the tarball.

@f-f, do you have ideas on what files must be preserved beyond those included in the `targets` key? Some that come to mind:

* `purs.json` file
* LICENSE file(s)

**Comment by f-f** [comment]
I think a good reference here is [the spec for NPM's `files` field for `package.json`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files).

In particular:
> Certain files are always included, regardless of settings:
> - `package.json`
> - `README`
> - `LICENSE` / `LICENCE`
> - The file in the "main" field

They also _always_ exclude some files, which would also be a nice thing to do.

I think the only real question that comes to me after reading their spec is: should we have a `files` key as well, or should we use `targets` to allow users to list files to be included in the package? (I'm leaning toward the latter)

**Comment by thomashoneyman** [comment]
We _could_ introduce an optional `files` key, which allows users to specify files that should be included in addition to the required files (the targets, `purs.json`, etc.). But in my experience of PureScript packages I don't think it's necessary and so I'm leaning away from it.

**Comment by f-f** [comment]
Yeah, let's not go that route for now (adding keys later is always possible, but taking them out is not)

So, to recap we will:
- include all the files specified by the targets
- always include a certain files (if present? What to do if not present?)
- always exclude a list of files, roughly following the blueprint of what NPM does

**Comment by thomashoneyman** [comment]
> always include a certain files (if present? What to do if not present?)

Some files are required (the manifest), and we will always include them; your package will fail to upload if they aren't present. Some files are not required (a LICENSE file), and we will include them if present and won't if not.

**Comment by f-f** [comment]
How about the `README`? IIRC uploads to Pursuit will be wonky if that's missing. We could also skip it for the legacy packages, and require it for the new ones.

**Comment by thomashoneyman** [comment]
As written in [this comment](https://github.com/purescript/registry/pull/309#issuecomment-1022561203), I no longer think this is worth doing, but more discussion can be found that link.

**Comment by thomashoneyman** [comment]
(However, it may still be worth _excluding_ some specific files, like version control directories).
