### ISSUE TITLE
Proposal: Separate JSON types from spec types

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#298]
As described in #270, we'd like to provide more idiomatic PureScript types for registry types like `Metadata` and `Manifest`. 

Before we launch into that effort, I'd like to propose that we explicitly separate types meant for use within the registry codebase from types meant to capture the spec and its representation in JSON. In other words, for all types that are part of the registry spec, we will have two representations within the registry: one that faithfully captures how it ought to be represented in JSON, and one captures how it ought to be represented in idiomatic PureScript.

@colinwahl originally suggested to this me, as it's what we do at work, and the structure works well.

### The Problem
We can take the `Manifest` type as an example:

https://github.com/purescript/registry/blob/1491929cad6db3a84d0f898e9c9118ff8dcbbb04/v1/Manifest.dhall

This type represents targets as a `Map Text Text`:

```dhall
targets : Map Text Target
```

...which maps to a JSON structure something like this:

```json
"targets": { "lib": { }, "test": { } }
```

...but we happen to know, in PureScript, that a `Manifest` _must_ have a valid `lib` target. And so the current representation of `Manifest` is a weird in-between of the JSON and the PureScript we'd like to have:

https://github.com/purescript/registry/blob/1491929cad6db3a84d0f898e9c9118ff8dcbbb04/ci/src/Registry/Schema.purs#L15-L23

https://github.com/purescript/registry/blob/1491929cad6db3a84d0f898e9c9118ff8dcbbb04/ci/src/Registry/Schema.purs#L39-L42

We sort of parse packages into valid `Manifest`s, but we continue to admit cases that shouldn't be possible (like a missing `lib` target). This leads us to use `unsafeCrashWith` and `unsafePartial` in the codebase when we _know_ a package should have a `lib` target and we need to access it, which is a major code smell.

However, if we were to change the representation of a `Manifest` significantly, then the JSON encoding and decoding becomes much more complicated.

### Proposal

The primary issue is that our types are doing double-duty: they represent structures we manipulate in the registry, _and_ they map to the JSON described in the registry spec. This causes them to perform poorly at both. My proposal is that we explicitly separate these concerns.

Instead of one `Manifest` type, we should have two. The first type is the PureScript representation and it should have no JSON instances. The second type is the JSON representation, which does have the `RegistryJson` instance. Then, we have functions that map from the JSON representation to the PureScript representation. It is in this transformation from one to the other that we can do whatever parsing and validation we need.

Specifically, I think we ought to adopt a directory structure something like this:

```
Json
  - Manifest.purs
  - Target.purs

Schema
  - Manifest.purs
  - Target.purs
```

where the JSON representations are separated from their PureScript representations.

**Comment by colinwahl** [comment]
I made the initial suggestion, so I agree with the general idea :D 

Are there any types where the PureScript idiomatic representation matches the schema representation? I wonder how we would handle that. Ideally we wouldn't have to do the extra work for those.

**Comment by thomashoneyman** [comment]
We've had a brief chat about this in the registry call and agreed on a different directory structure:

```
-- All the rich PureScript types
Schema.purs
-- All the on-the-wire types, decoding, etc.
SchemaJson.purs
```

**Comment by f-f** [comment]
Is this still relevant now that `targets` is not a thing anymore?

**Comment by thomashoneyman** [comment]
Yea, at this point the schemas are so close to the JSON that we may as well not go forward with this. Thanks!
