### ISSUE TITLE
Proposal: Rename purs.json to .purs.json

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#325]
Currently we specify that PureScript manifests are located in a manifest file named `purs.json`:

https://github.com/purescript/registry/blob/33eedbf9dd00ad6bbee75689c30f931fcb31adda/v1/Manifest.dhall#L3

Manifest files are _only_ used for publishing to the PureScript registry (and by extension to Pursuit and the package sets). They do not contain sufficient information for a package manager to manage a PureScript project using the manifest file alone. For that reason, any package manager for PureScript that admits configuration will have its own configuration file format. For example, Spago relies on a `spago.dhall` file that can be used to generate the `purs.json` file when it comes time to publish.

The general idea is that manifest files will typically be generated by package managers and are meant for PureScript infrastructure rather than PureScript readers. It's certainly _possible_ to edit these files by hand, but they're not an integral part of project management in the way that package manager files typically are (like a `spago.dhall` file).

I think that the `purs.json` file would be better suited by being renamed `.purs.json` to emphasize its role as a configuration file not essential to normal package management and a file that is rarely meant to be edited by the user directly.

**Comment by f-f** [comment]
I originally proposed this to you, so I agree 100% :smile:

**Comment by thomashoneyman** [comment]
One potential reason to _not_ do this change is that some globbing implementations ignore dotfiles by default. It isn't necessarily an issue, but here's one example of it inadvertently biting me:

https://github.com/purescript/purescript/pull/4233/commits/4867d06258a45f3d52d76d40e3c96b5be7c41f5e

I can't really think of when else this will be an issue, but it's a possible concern.
