### ISSUE TITLE
Support creating a resolutions file when publishing packages

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#326]
We would like to automatically publish packages to Pursuit when they are uploaded (see #154). To do that, we need to create a resolutions file for newly published package versions. The resolutions file format looks like this:

https://github.com/purescript/purescript/blob/f9f75f43bd1bdbc1e866fdba876582385e3f4c65/src/Language/PureScript/Publish.hs#L298-L317

When we upload a file we only have dependency ranges; we will have to implement at least a simple solver to resolve what specific version to put for each dependency of the package so we can create this resolutions file. If producing the build plan fails, then we will have to fail the Pursuit upload and tell the user to try manually through other means.

**Comment by thomashoneyman** [comment]
@colinwahl I seem to remember you'd implemented something along these lines when putting together the toposort for package versions so we can check that a package's dependencies are all present in the registry. Do you think it could be repurposed for this?

**Comment by colinwahl** [comment]
@thomashoneyman yes, I had something similar here: https://github.com/purescript/registry/blob/706a18ebb598e4ea76bb196167522f6d2bb5ee75/ci/src/Registry/PackageGraph.purs (before it got changed slightly - the code doesn't look like this anymore).

This code iterated over a set of package dependency constraints, "solving" them by finding packages with no dependencies, then going through the set of dependencies marking that package as resolved in dependencies, and looping. It was a bit slow, but I think we can repurpose something from there to work here!

**Comment by f-f** [comment]
It's worth taking a look at [Elm's solver](https://github.com/elm/compiler/blob/8dfdde748a7d4711c0242a82222efbc11307344f/builder/src/Deps/Solver.hs), I believe we could reuse that easily.
If we go for "option 2" in https://github.com/purescript/registry/issues/327#issuecomment-1030591507 then we could just stick the solver in Spago, which we'll need to do anyways sooner or later

**Comment by thomashoneyman** [comment]
We may need to implement a solver in PureScript either way, because the only way Pulp users can use the new registry is if we add a solver to Pulp. It’s either that or make Pulp users switch to Spago, once Spago has a solver.

**Comment by f-f** [comment]
Pulp never did package management, it's only a build tool. You can use bower (that has a solver) or psc-package with it (package sets) - do you think we should plan for it to start doing package management itself?

**Comment by thomashoneyman** [comment]
You're right, Pulp never did package management proper, I've just always associated it with that due to the Pulp + Bower combination. So I guess Pulp users can only use the new registry if Pulp users have a way to download and install packages from it, which includes having a solver. We would have to build that for Pulp users, turning it into a package manager proper.

Given our bandwidth, that seems unlikely 😆 Pulp users may simply have to become Spago users to use the new registry.

**Comment by f-f** [comment]
I just realized that if we go for the path of "asking the local package manager to provide a plan in the API operation" then we don't have to worry for a while about this, since Spago with package sets already has a clear build plan and could just submit that.

**Comment by thomashoneyman** [comment]
I'm OK with this. We could adjust the API to accept a plan, perhaps of this shape:

```purs
{ compiler :: Version
, resolutions :: Map PackageName Version
}
```

where the compiler version tells us how to build the project in CI, and the resolutions are exactly the same as the `dependencies :: Map PackageName Range` just fixed to a specific version.

If you agree, I could go ahead and take care of this.

**Comment by f-f** [comment]
Yeah, let's try this out!

**Comment by f-f** [comment]
This is now completed! (even with optional plans) :tada:
