### ISSUE TITLE
How do users manually publish to package sets or pursuit if automatic publishing fails?

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#327]
In #154 and #156 we asserted that we'd like to automatically publish packages to Pursuit and to the package sets. However, there are reasons why this can fail.

Pursuit publishing can fail if we can't produce a resolutions file (#326), and perhaps for other reasons. Package sets publishing can fail if the package version has dependencies that aren't already in the set, or if the version breaks compilation for the set.

In both cases a user's package version will not make it into Pursuit or the package sets, and we need to give them an alternate way to get their package version there. For Pursuit, perhaps that's ensuring that Pursuit retains the ability for people to upload their packages without going through the registry (though the package would have to be in the registry, of course). For package sets, perhaps it's just a manual process on the `package-sets` repository where package sets curators manually intervene.

Regardless of the decision, we need to include this in the spec.

**Comment by f-f** [comment]
There are two reasons why the generation of docs can fail:
1. the project doesn't build - this could be either because it might build on some other compiler version, o because it would not build with any compiler version
2. the project builds but we are not able to find a plan (this is #326 that you mentioned)

I think we have two possible ways to go at this:
1. we figure out all this stuff in CI. That entails potentially trying to compile with many different compiler versions and build a couple of different build plans
2. we ask the user to do this (so the package manager would gather this info locally) and take that in input (that is, the compiler version and the build plan) when publishing. We still have to have different compilers available in CI, but we have to build only once

**Comment by thomashoneyman** [comment]
There is a third reason why docs generation can fail: the project is a legacy project using Spago. In that case, there is no manifest format that `purs publish` understands, and so docs cannot be generated. We could generate a `purs.json` file for the user, but `purs publish` will reject publishing a package with a dirty source tree; it takes the version from the checked-out tag, so there's not much we can do here.

The solution there would be to generate a `purs.json` (or `bower.json`) file for the Spago user and ask them to commit that. Then we can generate docs for them.

**Comment by f-f** [comment]
But we are already generating a `.purs.json` file when importing legacy packages, so there's no need to commit that?

**Comment by f-f** [comment]
So if the locally-running Spago is providing the build plan and the compiler version, then I think the only thing we'd need to make this work would be to make `purs publish` more lenient and accept a version from the `purs.json` instead of getting it from git.

**Comment by thomashoneyman** [comment]
> So if the locally-running Spago is providing the build plan and the compiler version, then I think the only thing we'd need to make this work would be to make purs publish more lenient and accept a version from the purs.json instead of getting it from git.

The first thing we have to do is update `purs publish` to read the manifest.

After that, `purs publish` verifies the version being published. It makes sure you've checked out a valid tag, and then it checks GitHub for the matching tag on the repository. This verification won't work for the registry, because we support monorepo setups and the Git tag doesn't mean the package version. So we definitely have to update `purs publish`'s verification when using a `purs.json` file; my suggestion that stays close to the Bower check is that `purs publish` verifies that the version from the manifest is also in the registry, at the same commit that is currently checked out.

These changes to `purs publish` are tracked in this proposal on the compiler repository:
https://github.com/purescript/purescript/issues/4231

As you said, we can also relax the `purs publish` check so that it doesn't verify the version in the `purs.json` file. I would guess that the compiler team won't want to do this, and I haven't thought through the possible failure cases if we don't verify the version -- maybe it's OK.

These changes are necessary to publish packages using the new manifest format. But they don't help us with legacy Spago projects, because `purs publish` has a restriction that you cannot publish with a dirty working tree. That means that generating a `purs.json` file for a legacy Spago package is not enough -- it has to be committed, and that commit has to match with the version you're publishing, as previously described.

That gives us two options:

1. Relax the `purs publish` restriction on dirty working trees. This would allow you to check out a commit, make some changes, and then publish the dirty working tree.
2. We can ask Spago users to commit the `purs.json` file if they want their package uploaded to Pursuit. Without committing the manifest and using that commit to publish, we can't upload their package for them.

I don't think we should do option (1), because then the code published to Pursuit for a particular version doesn't necessarily match with the _actual_ code at that version. Option (2) is the same problem that Spago users currently face, and the reason why we make them generate a `bower.json` file and commit it before they can publish to Pursuit.

**Comment by f-f** [comment]
Thanks for the explanation. My concerns with committing a `purs.json` file (at this stage) that make me think it's not a viable option are that:
1. then we are committing to this specific `Manifest` schema immediately
2. this is not a "legacy" publish anymore, i.e. we skip steps of the staged deployment of the Registry and immediately go to the full blown API pipeline

I wonder if we can relax the restriction on dirty-working trees, but _only_ if the only dirty file is the `purs.json`? That would allow us to do the work in CI.

**Comment by thomashoneyman** [comment]
> I wonder if we can relax the restriction on dirty-working trees, but only if the only dirty file is the purs.json? That would allow us to do the work in CI.

This is the easiest option, and I'm in favor. I think even if you edit your manifest and lie about the contents, enough is checked against the registry to verify it, and it would be a lot of intentional effort to go through just to publish bogus docs to Pursuit (the worst consequence).

For the time being, I'll just go ahead and add that to my implementation of the new `purs publish` command and see if the rest of the compiler team is OK with it.

**Comment by thomashoneyman** [comment]
We've talked through how to minimize the risk of automated publishing failing; what about if it _does_ fail anyway, like Pursuit is down? The `purs publish` command is still the way to publish to Pursuit manually, so perhaps we should add support for this to Spago, the same as exists for Pulp?

And as far as the package sets go, if the package fails to be added to the set, what is the manual process for adding it? Open an issue on the registry or on the package sets repository?

**Comment by afcondon** [comment]
> ...and it would be a lot of intentional effort to go through just to publish bogus docs to Pursuit (the worst consequence).

Isn't that a bit of a hostage to fortune tho? in that, in some ultra-successful PureScript future where modifying the docs for some package enables social-engineering of vulnerabilities somewhere?

Not disagreeing with your conclusions or proposals tho, but maybe it's worth creating an issue for that potential attack vector.

**Comment by thomashoneyman** [comment]
As per the registry call this morning, we discussed tying Pursuit to the registry, so that the only way to publish to Pursuit is via the registry. This sidesteps issues with `purs publish` being abused to create bogus docs that then get pushed to Pursuit; instead, `purs publish` would be able to push docs to Pursuit that reflect the contents of the tarball packaged to the registry.

However, I don't think we yet have an explanation of what you can do if the registry fails to push your package to Pursuit. How do you indicate that the registry should retry?

**Comment by f-f** [comment]
If the flow fails you can post another JSON payload (with the same ref or a new one, depending if you need to fix things or not) to the same issue, and it will retry the pipeline

**Comment by thomashoneyman** [comment]
We don't currently retry the pipeline, so I've created an issue to track it here:
https://github.com/purescript/registry/issues/343#issue-1128978783

**Comment by thomashoneyman** [comment]
This issue has been addressed at this point. First, users can re-submit their package to the registry if docs publishing fails; the registry will detect if the package has been uploaded before but there are no docs on Pursuit and will automatically retry publishing the docs. Second, we have a manual package sets update process by which users can add their own packages to the set if possible.
