### ISSUE TITLE
Proposal: Unify the 'Addition' and 'Update' operations

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#332]
The registry API consists of three operations: `Addition`, `Update`, and `Unpublish`:

https://github.com/purescript/registry/blob/62b93f1cf16d97520979925b5a0fcc525f6c77fc/v1/Operation.dhall#L10-L13

The first two operations apply when a user wants to publish their package. An `Addition` is for publishing a brand-new package the registry doesn't know about, or publishing a version of an existing package from a new location. An `Update` is for publishing a new version of a package already in the registry. They differ in a few ways: an `Update` doesn't require a location, for example, because we just look up the package's existing location we've stored.

However, I think separating an `Addition` from an `Update` is unnecessarily complicated, both for users and for us. Their implementations are essentially the same, modulo some verification checks to ensure (for example) that you aren't trying to `Update` a package that doesn't exist (and therefore you should have used an `Addition`). I think we can do away with the distinction between the two and just have a `Publish` operation and an `Unpublish` operation.

For context, here's the implementation of an `Addition`:

https://github.com/purescript/registry/blob/62b93f1cf16d97520979925b5a0fcc525f6c77fc/ci/src/Registry/API.purs#L108-L114

And here's the implementation of an `Update`:

https://github.com/purescript/registry/blob/62b93f1cf16d97520979925b5a0fcc525f6c77fc/ci/src/Registry/API.purs#L116-L123

In both cases we check for the existence of a metadata file. If it's an `Addition` and we can't find one, we create it; if we do find one, then we redirect to be an `Update` instead. If it's an `Update` and we can't find a metadata file, we just throw an exception. Otherwise, though, we just move directly into `addOrUpdate`, where we use the metadata's `location` field to fetch the repository to package, at which point we switch to using the package's manifest for further processing.

This all has me asking: why is the distinction between an `Addition` and an `Update` necessary? There isn't much difference between the two operations, and these distinctions lead to unnecessary ambiguity. In each case we can have a clearer API by unifying the options:

1. An `Addition` takes a package location, and an `Update` does not. This is done because we don't need to know the package location for an update -- we can take it from the existing metadata. But it has a downside: if you change your repository location, you have to process an `Addition` even though your package already exists. It's not clear how package managers are supposed to know when to send an `Addition` or an `Update`. We can resolve this by _always_ requiring a location when publishing a package. Package managers have to know this anyway, so there's no added inconvenience, and it lets us remove the ambiguity around changing repo locations.
2. An `Addition` takes an `addToPackageSet` flag, and an `Update` does not. This is done because presumably you decided if your package was going to be a "package set package" when you first added it. But it has a downside: you can't change your decision about whether your package should be in the package sets. It feels like if we want to let users make this decision, they should be able to decide on a per-version basis, not just choose once for the whole lifetime of the package. We can resolve this, too, by always accepting an `addToPackageSet` flag.

Even worse, this ambiguity has already lead these two operations having buggy implementations. For example, when you submit an `Addition`, but we already have some metadata about the package, then we go straight to `addOrUpdate` without updating the metadata location:

https://github.com/purescript/registry/blob/62b93f1cf16d97520979925b5a0fcc525f6c77fc/ci/src/Registry/API.purs#L110-L112

So what should we do? I think we should unify the two operations into one `Publish` operation:

```diff
 let Repo = ./Repo.dhall 

 in 
-   < Addition : { packageName : Text, newPackageLocation : Repo, newRef : Text, addToPackageSet: Bool, legacy : Bool } 
-   | Update : { packageName : Text, updateRef : Text, legacy : Bool } 
+   | Publish : { packageName : Text, location: Repo, ref : Text, addToPackageSet: Bool, legacy : Bool } 
    | Unpublish : { packageName : Text, unpublishVersion : Text, unpublishReason: Text } 
   > 
```

The difference is that we always take the package location and whether to add it to the package sets as part of the `Publish` operation. This removes any ambiguity about the difference between an addition and an update, which lowers the cognitive load for users and for implementors.

**Comment by thomashoneyman** [comment]
We could also take things a step further by removing the `legacy` flag. We know a package is a legacy package if it doesn't have a `.purs.json` file. If there is no `.purs.json` file then we fall back to the `bower.json` or `spago.dhall` files in the repository, and if they don't have those files either then we reject the package. After a year or so, when we no longer accept legacy packages, we don't have to remove the `legacy` flag from the API -- we just change its behavior to be an immediate error. This change makes one less thing for package managers to have to deal with.

**Comment by f-f** [comment]
> This all has me asking: why is the distinction between an `Addition` and an `Update` necessary? There isn't much difference between the two operations, and these distinctions lead to unnecessary ambiguity

They are conceptually different scenarios: an `Addition` registers a name to the Registry and then performs an `Update`, while the `Update` only publishes a new version

> However, I think separating an `Addition` from an `Update` is unnecessarily complicated, both for users and for us. Their implementations are essentially the same, modulo some verification checks to ensure (for example) that you aren't trying to `Update` a package that doesn't exist (and therefore you should have used an `Addition`)

This is an implementation detail that is part of the contract between package managers and the registry, users don't get to deal with this.
The complexity that it gives us is those 20 lines of code that you quote, but it's a well-worth tradeoff since it allows us to solve the problem of "changing the repo URL", as I explained in https://github.com/purescript/registry/issues/331#issuecomment-1030825172

> An `Addition` takes a package location, and an `Update` does not. This is done because we don't need to know the package location for an update -- we can take it from the existing metadata.
> But it has a downside: if you change your repository location, you have to process an `Addition` even though your package already exists.

Note that we _have_ to take the URL from the metadata because we can't trust whatever is coming from the API.
This is why we can't process URL updates from the API, which means that they wouldn't happen with `Addition`s.

> It's not clear how package managers are supposed to know when to send an `Addition` or an `Update`

For what we care they can always supply `Additions`, and we'd throw away the unnecessary information and turn them into an `Update` when the package was already registered.

> Even worse, this ambiguity has already lead these two operations having buggy implementations. For example, when you submit an `Addition`, but we already have some metadata about the package, then we go straight to `addOrUpdate` without updating the metadata location

...which is why this is not a bug, but it's working exactly as intended.

----

> An `Addition` takes an `addToPackageSet` flag, and an `Update` does not

This is a historical accident that came from the fact that we added this flag long before we specced properly how to do package sets here. I think we could just take this flag away and always try to add packages to the set?

----

> removing the `legacy` flag. We know a package is a legacy package if it doesn't have a `.purs.json` file

I think this is a good idea, yeah. Again the `legacy` flag was added when we did not know better - now we know that we can just use the Manifest existence to decide which path to take in the API

**Comment by thomashoneyman** [comment]
As per the discussion in https://github.com/purescript/registry/issues/331#issuecomment-1032131680, I had thought that an addition is being used both to register a new package _and_ to change its location. That's cleared up for me, and it's obvious they need to remain separate, so I'm going to go ahead and close this.
