### ISSUE TITLE
Is it safe to remove the `isPackageSetInRegistry` check?

### ISSUE THREAD

**Issue by colinwahl** [purescript/registry-dev#336]
Now that our published package sets are parametric over the `externalPackage` type - it shouldn't be possible for us to construct a value with the `Registry.External` type. 

In that case - is it safe to remove the `isPackageSetInRegistry` check?

**Comment by f-f** [comment]
@colinwahl that's correct, we can remove it!

**Comment by colinwahl** [comment]
Great, I'll open a PR
