### ISSUE TITLE
Make published date optional in version metadata, unless we can guarantee we can always get it

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#342]
We store a package's publication date in metadata:

https://github.com/purescript/registry/blob/fb20bec4af37a96353bc98c3f30391c77e2472d9/ci/src/Registry/Schema.purs#L164

...which we retrieve in the GitHub provider by looking at the commit:

https://github.com/purescript/registry/blob/fb20bec4af37a96353bc98c3f30391c77e2472d9/ci/src/Registry/API.purs#L151

However, since we are provider-agnostic, there is no guarantee that we will be able to retrieve the date of a given `ref`. For example, in the registry call this morning @f-f described fetching from a filesystem online, where we may not necessarily be able to retrieve a published date.

This isn't critical information; there's no harm in making it optional if we do end up always being able to figure this out, but there is harm in changing this field from required to optional as far as package managers are concerned (it'd be a breaking change for anyone consuming metadata).

**Comment by f-f** [comment]
Why should this be optional?

- for legacy packages we are only asking GitHub, which means we always get the date
- for non-legacy packages we can use the time of when we run the pipeline (which is the "time of publishing"), which we always have

I.e. trying to figure out a publishing date that happened in the past is only to be done for legacy packages, which fortunately are all on GitHub :slightly_smiling_face:

**Comment by thomashoneyman** [comment]
I think it's preferable for the publish date to reflect the time the ref was cut, rather than reflect at what time the package was pulled into the registry. Put differently, I would find it odd to see a package's published date on Pursuit only to realize that it's not the date the release was published on GitHub. Especially since all legacy packages rely on the publication time of the ref, not the time they hit the registry.

If we'd like to keep this field required, then I'd suggest we specify that publishing follows these rules:

1. We attempt to use the package `ref` -- which identifies the code at a point in time -- to determine the time of publication.
2. If we cannot do that, we fall back to using the time the package was published by the registry

For all packages that use Git (including GitHub, Sourcehut, etc.) we can pull this information from the tag or commit itself. But as we grow to support other kinds of refs it may not be possible to collect this information, and so we'll just use the registry publish time instead.

Does this work?

**Comment by f-f** [comment]
Yes, this sounds great!
