### ISSUE TITLE
Allow users to reattempt publishing a package

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#343]
In https://github.com/purescript/registry/issues/327#issuecomment-1034145556 @f-f stated that users should be able to trigger the registry CI to reattempt publication to Pursuit (and presumably package sets) if something unexpectedly went wrong the first time (such as a network error).

However, right now we exit the pipeline if you attempt to re-run it for an existing version:

https://github.com/purescript/registry/blob/fb20bec4af37a96353bc98c3f30391c77e2472d9/ci/src/Registry/API.purs#L277

Instead, it sounds like we should detect the existing version, and then verify that the follow-on steps completed successfully:

1. The package was uploaded to the storage backend
2. The package was uploaded to Pursuit
3. The package was added to the package sets

If we detect that any of these steps did not complete, then we reattempt them, reporting errors to the user as usual.

**Comment by f-f** [comment]
If the publishing fails this version does not exist, as we commit the metadata as last thing (or if we don't, we should)
The pipeline _does_ retry in that case, we explicitly tested this when first implementing the API entry point.

**Comment by thomashoneyman** [comment]
We do commit the metadata as the last thing, other than pushing to the registry index (which is fine). This covers the first case: your package is only considered published if we uploaded it.

But it doesn't answer Pursuit and the package sets. Right now these are unimplemented so it's not clear from the code where we plan to slot them into the process. 

What should happen if your package was uploaded to our storage backend, but failed to be uploaded to Pursuit? Do we bail out the whole process and say your package was not uploaded, and thus never write the metadata file? In that case we should delete the upload we pushed to the storage backend (or else we'll have packages published without corresponding metadata files). Or do we consider your package published, and just tell you that Pursuit failed, and you can retry? In that case we have to change the code, because you'll have a metadata file asserting the version exists, but we want to retry the pipeline anyway. 

What about package sets? We certainly don't want to block your package from being uploaded just because it can't be added to the package sets. So in that case, we still need to update the code to not throw right away if the version is already published. They should be able to retrigger the pipeline to try and get it added to the package sets.

Part of the problem here is that we don't have support for pushing to Pursuit _or_ to the package sets right now, so it's not clear where they are going to slot into the process by looking at the code alone. What do you think of stubbing out no-op operations in the correct place, and implementing the retry logic, just so that we can demonstrate how it _should_ work when we get around to the underlying implementation?

**Comment by f-f** [comment]
Yeah, good points. I'll need to think more about all of this, but stubbing noop actions in the correct place sounds like a good way forward!
