### ISSUE TITLE
Proposal: Publish packages via a separate repository

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#344]
In the registry call this morning, @f-f and I discussed how GitHub issues are used for all API operations for the registry. However, GitHub issues are _also_ used to track development on the registry and as a communication channel between registry trustees and registry users in the case something goes wrong.

As a registry trustee and registry developer, though, this is problematic. If I watch the repository so I can stay on top of issues, then I am going to be flooded with irrelevant issues about users uploading their packages. I guarantee I'll be forced to unwatch the repository, and then I'm going to miss important issues.

I am proposing that we set up a separate repository for exercising the API from the repository we use to develop it. Either we transfer the current repository to a new one (`registry-dev`?) and use the `registry` name for users, or we keep the repository where it is and create a new repository for users (`registry-api`?).

We can still push commits from one repository to another, so I don't believe this will restrict anything we're currently doing. It'll also be nice to be able to separate user documentation from maintainer documentation!

**Comment by thomashoneyman** [comment]
Of the options here, my preference would be to run registry development from a repository named `registry-dev` or something similar, leaving `registry` to be the place where the package metadata and package sets are located (ie. the place where package managers and users interact with the registry).

To transition, I believe we could take these steps:

1. Transfer this repository to `purescript/registry-dev`, so that the issues and pull requests are preserved
2. Create a new repository named `purescript/registry`
3. Copy over the relevant artifacts, ie. the `metadata` directory, the `sets` directory, user-facing documentation

I can take care of the transition if we agree this is how we'd like to do it. But for now I'm putting the `blocked` flag on, because we almost certainly don't want to do this until we are close to launching the registry alpha.

**Comment by f-f** [comment]
This plan sounds great!

A few more notes:
- I'd like @pacchettibotti to be the only account that can write to the new `registry` repo, and we wouldn't accept PRs
- we shall remember to update the current publishing instructions to point to `registry-dev` for updating the `new-packages.json` file (does that require patching `pulp`?)

**Comment by thomashoneyman** [comment]
As discussed in the registry call this morning, we do need to patch Pulp to point at the `registry-dev` repository when we migrate, and we should leave a note for old Pulp users in the `registry` repository pointing them over to `registry-dev` too.
