### ISSUE TITLE
Discussion: Use of 'repository' terminology

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#345]
In https://github.com/purescript/registry/issues/331#issuecomment-1032266571, @f-f made it clear that packages do not need to be stored in Git repositories; in fact, all we really care about is that we can retrieve a package's source files given a location and a unique reference to the source files corresponding with a particular version. @f-f mentioned the terminology "tarball provider" as a more accurate name than "git repository" for picking up package sources from ie. the GitHub API.

However, the spec and schemas make many references to packages being Git repositories, and the use of "repository" to describe where we get a package's sources from is used pervasively.  

Examples include the `Repo` type:

https://github.com/purescript/registry/blob/a9b6251d4d9a6629e72baa8e53ec9f6ba1e6a7ca/v1/Repo.dhall#L3

and the `Manifest` type:

https://github.com/purescript/registry/blob/f62ee2560f1de4a5fc90becfed13511239559f48/v1/Manifest.dhall#L22-L23

and the `Metadata` type:

https://github.com/purescript/registry/blob/cc22a35f0fecf5d88efe88e90b2162a633a3924e/v1/Metadata.dhall#L17-L18

I think we need to remove these references to "git repositories" and "git refs". In addition, I think we should seriously consider renaming the `repository` field in the manifest and the `Repo` type to terminology that makes it more obvious that packages don't _have_ to be Git repositories, even if that's all we support at first.

The `Metadata` type already uses a potential alternative:

https://github.com/purescript/registry/blob/cc22a35f0fecf5d88efe88e90b2162a633a3924e/v1/Metadata.dhall#L27-L28

I feel like the name `location` and the description "a pointer to the code" are much more accurate to the registry's agnostic stance than the name `repository`, and I think it's worth considering standardizing on this instead.

**Comment by f-f** [comment]
Yes, I'd also prefer to use `location` everywhere!
