### ISSUE TITLE
Check that compile build as part of uploading

### ISSUE THREAD

**Issue by colinwahl** [purescript/registry-dev#360]
As part of our package[1] upload CI checks, we'd like to ensure that packages compile, and reject the upload if they don't.

To do this, we need to figure out a few things:
1. What version of the PureScript compiler do we use?
2. How do we compile packages if they may be for different backends?
3. How do we get all of the dependencies for the package (required for `purs` to compile)

For (1), @thomashoneyman and I were thinking that we could use the last two major versions of the compiler, first building with the latest major version, then checking with the last major version, then failing if the package compiled with neither. Should this check fail, we can notify the registry maintainers to see if something needs to change. The motivation behind this is that only `0.13+` is available through `easy-purescript-nix` at the moment. Presumably `0.13` support will stay once `0.15` releases, so maybe we can expand to checking more versions in the future.

For (2), we should be able to compile with `purs compile ... -g corefn`, which should be able to type check the package regardless of the backend used.

For (3), there are two options: right our own solver, or push that to the user (i.e. the package manager). I believe that the latter option is preferred. To handle this, we can add some sort of `Map PackageName Version` parameter which is a list of specific versions for each transitive dependency required for the package to build. We can then fetch the tarballs from the registry to get access to the source code for each dependency & pass them in to the `purs compile` check.

[1] really, this is a package at a specific version, but I'll just call it a package

**Comment by f-f** [comment]
What's the usecase for compiling packages when uploading? Only to generate docs? If yes, in https://github.com/purescript/registry/issues/326 we agreed that, as you mention in (3), users will be required to provide a build plan (including the compiler version) when publishing a package.

**Comment by thomashoneyman** [comment]
We have to do this to generate docs, and we could also say that your package has to compile to be registered if we wanted to. The implementation is the same either way, it's just whether we:

1. Run checks and register the package, then compile the docs, and fail to push to Pursuit if compilation fails
2. Add compilation to the checks, considering failed compilation a failed check, so the package is only registered if it compiles. At that point, push the docs to Pursuit (which now will definitely succeed, modulo network errors).

**Comment by thomashoneyman** [comment]
We've started work on this, by the way!

**Comment by f-f** [comment]
Right, I see. I feel like compilation being part of the checks is the option that makes most sense!

**Comment by thomashoneyman** [comment]
This was completed in #402.
