### ISSUE TITLE
Test utils for generating manifests

### ISSUE THREAD

**Issue by colinwahl** [purescript/registry-dev#373]
There are existing tests that need to have a valid manifest hierarchy to check behavior (i.e. the registry index tests use the manifests defined here: https://github.com/purescript/registry/blob/master/ci/test/Support/Manifest.purs). Creating these by hand is quite tedious & error prone, especially getting the dependencies right. In the near future, for testing that we are correctly validating build plans for generating pursuit docs & creating the correct resolutions file, we will be in need once again of a valid manifest hierarchy.

Ideally we would have some way of generating these manifests that depend on each other automatically, either by requesting new manifests one-by-one or by generating a whole tree of manifests at a time. I'm not exactly sure what it'd look like or how it'd work at the moment, but here are a few important points I can think of:

* We may need to be able multiple versions of a single package (this is used in the registry index tests)
* Dependency lists should only refer to items that we've already generated a valid manifest for

@thomashoneyman Suggested that we could have a predefined set of "dependency" manifests, and then our generation logic could just use a subset of those as dependencies, only generating the other information. This may work, but could also lead to a pretty flat hierarchy. If that's a problem, we'll need to do a bit more thinking.

**Comment by thomashoneyman** [comment]
Is this fixed in #378?

**Comment by colinwahl** [comment]
Aha - yes, I forgot to link the issue.
