### ISSUE TITLE
Automated upgrade support for breaking changes

### ISSUE THREAD

**Issue by milesfrain** [purescript/registry-dev#46]
Could we setup a framework to enable automated (or mostly automated) upgrades for dependents of packages with breaking changes? I'm envisioning the ability to run `spago --upgrade-set` and have code changes automatically applied when possible (with user's permission of course).

We could start by just listing which packages were detected as having breaking changes, and then link to their release pages. For example:
```
spago --upgrade-set
...
react-basic-hooks upgraded from v4.2.1 to v5.0.0
  Migration guide: https://github.com/spicydonuts/purescript-react-basic-hooks/releases/tag/v5.0.0
```

We could take this a step further by allowing upgrade scripts to automate some of these operations. For example, with the above upgrade, automatically rename:
```React.Basic.Hooks.component```
to:
```React.Basic.Hooks.reactComponent```

I suspect there's a nice way to define these transformations and then let the parser and/or compiler help out with applying them. The registry seems like a good place to store these automated upgrade instructions. For example: `packages/foo/v2.0.0.upgrade` to handle updating dependents of `Foo` from the latest `v1` to `v2`. In cases where no manual upgrade steps are required, we could automate PRs to all dependent packages in a package set, so that trivial (yet breaking) API changes are painless. We could also investigate automated upgrades for breaking compiler changes. There's an effort to [do this with Elm](https://github.com/avh4/elm-upgrade), but I think we could do even better. Perhaps even less manual coordination would be required for 0.15.0+ releases https://discourse.purescript.org/t/updating-the-ecosystem-for-upcoming-0-14-0-release/1144

**Comment by hdgarrood** [comment]
This has occurred to me before too and I think it would be a super useful thing to have. However, I feel like it should be prototyped as a separate project initially; the registry project is quite ambitious already, I think, so I would suggest that we might not want to increase its scope right now.

**Comment by f-f** [comment]
Agreed that this would be amazing to have but it'd be best prototyped in a separate project :+1:

**Comment by f-f** [comment]
@milesfrain maybe making a post on Discourse could be the best way to move this forward, so that all the interest people could get together and prototype something? I'd like to keep the backlog as actionable as possible, so I'll close this for now
