### ISSUE TITLE
Take over `purescript-fetch`

### ISSUE THREAD

**Issue by sigma-andex** [purescript/registry-dev#486]
Hi,
I would like to take over the `purescript-fetch` namespace for a new implementation of a `fetch` library that I'm currently writing (the target repo will be https://github.com/rowtype-yoga/purescript-fetch).

@rightfold could you please confirm that this is ok with you? Thank you very much

**Comment by thomashoneyman** [comment]
Feel free to open a PR transferring the package – delete the previous entry, and then add the new entry to `new-packages.json`.

We only allow reuse of a name if it doesn't have any published versions. It looks like `rightfold/fetch` does have several Git tags indicating releases, but none of them were able to be published to the PureScript registry (see the `metadata` directory in https://github.com/purescript/registry-preview) so this is OK.

Once @rightfold confirms that this is acceptable then I can merge the PR and process the transfer.

**Comment by no-longer-on-githu-b** [comment]
Let’s do it!

**Comment by thomashoneyman** [comment]
@sigma-andex if you'd like to go forward with this, go ahead and open the PR and I can merge it for you!

**Comment by sigma-andex** [comment]
> @sigma-andex if you'd like to go forward with this, go ahead and open the PR and I can merge it for you!

Just had another look and it is in the metadata (https://github.com/purescript/registry-preview/blob/main/metadata/fetch.json) or do I misunderstand what you mean? Is it ok anyway to transfer it?

**Comment by thomashoneyman** [comment]
Ah — well, in that case, strictly speaking, we shouldn’t transfer it in the case someone is depending on it, upgrades, and then suddenly the name points to a new library. However, I personally am fine with this given the age of the library and that you are a well-known member of the community so the security angle is less relevant. However, @f-f may disagree, in which case we’ll need to revert this. Going forward, though, a name already in the registry can’t be reused.
