### ISSUE TITLE
Proposal: Unify addition and update operations

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#524]
Currently we have an `Addition` operation and an `Update` operation. Their only difference is that an `Addition` takes a `newLocation :: Location` field that lets us know where to fetch the package source from, and an update does not (it reuses the location from the package metadata). I believe these were originally separate because it was possible to process transfers via these operations, but that's no longer possible. Right now we route both operations to the same `addOrUpdate` function, failing if it's an addition and no location was provided.

My proposal is that we have a single `publish` operation so the logic is unified. The validation requirements are detailed in #523, but in short, the payload would look like this:

```jsonc
{
  // Required: package name
  "package": "prelude",
  // Optional if an update, required if a new registration. If supplied and is an update, this will
  // be verified against the metadata.
  "location": { "githubOwner": "purescript", "githubRepo": "purescript-core", "subdir": "prelude" },
  // Required: version ref
  "ref": "v1.0.0",
  // Required: which compiler to use to build the package
  "compiler": "0.15.0",
  // Optional: what package versions to use for dependencies. If not specified we use the solver.
  "resolutions": { }
}
```

**Comment by f-f** [comment]
Should the `compiler` field be a range?

**Comment by thomashoneyman** [comment]
It could be, but I think we should expect that the provided compiler version range is valid and should halt the pipeline if compilation fails — so the version range is essentially the same as compiling with the top version of the range.

And I think to determine a package’s supported compilers we should try to compile as far back as we can regardless of the range provided.

So I don’t think there’s an advantage to taking a range unless it’s somehow easier for package managers.
