### ISSUE TITLE
Proposal: Include `compiler` version ranges in metadata

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#526]
I think a package's published versions metadata should contain a `compiler` field for each published version. When the package is uploaded this will be a range using the `compiler` field they sent in the API (like `>=0.15.3 <0.15.4`).  But then the build matrix kicks off, and then we adjust the range to be what we've discovered actually works (like `>=0.15.0 <0.15.5`). 

Unfortunately, old packages that we never compiled (those via the legacy importer) may not have a range unless we try to build them too (which we could).

We can use this info for example to determine what compilers are suitable for Spago or the package sets to use given a set of package versions: use the compiler admitted by their intersection. We can also display this information on Pursuit and use it to add a filter that only displays packages that support a particular compiler version.

**Comment by f-f** [comment]
Is this a duplicate of #255?

**Comment by thomashoneyman** [comment]
Oops, yes it is.
