### ISSUE TITLE
Implement structured effects in the dev codebase

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#563]
I plan to rework how we handle effects (like logging, making requests, using a cache, etc.) in the application.

### Background

In the last registry call we discussed some difficulties I've been having when implementing the new HTTP API. Specifically, the current codebase has a few patterns that are difficult to work with:

* The `Foreign` modules are meant to be low-level bindings, but instead we've got quite a lot of registry-specific code that's trickled into it, like the GitHub module relying on our cache effect and making specific authenticated requests to the registry rep, or the S3 FFI bindings looking for specific environment variables to be available. These modules shouldn't have registry-specific or environment-specific code if we can help it, because it dramatically expands the footprint you have to be aware of to make changes to things like GitHub requests.
* Most code is written `Aff` directly and can perform arbitrary effects, like throwing exceptions, writing to the file system, making requests, reading the Node process, logging, committing to GitHub, using the `git`, `purs`, and other command-line tools, and more.
* Code that is in `RegistryM` is barely better than unbounded `Aff`: most of the code is still in `Aff`, with `RegistryM` simply providing access to a tiny handful of functions (`throwWithComment`, etc.) and a minimal environment. All non-trivial code is still implemented in `Aff`, which makes plenty of functions essentially un-testable in a pure environment.
* The `RegistryM` monad itself is for all intents and purposes hardcoded to the GitHub environment -- we've got things like `Octokit` in the environment, functions like `throwWithComment` which assume access to an issue number to write a comment on, and so on. There is no abstraction over the now _many_ environments we execute in -- test fixtures, local dry runs, local runs that commit, GitHub containers triggered by comments, GitHub containers triggered by scheduled jobs, and a HTTP API running on the server.
* Abstracting effects makes it possible for Spago to use more registry functions directly and provide its own methods for things like reading manifests, logging, downloading packages, and so on.
* Implementing `RegistryM` as a record of handlers is problematic because the handlers cannot be mixed and matched or easily rely on each other -- for example, it's quickly becomes messy to implement functions to make GitHub requests that rely on a logging effect that can be handled separately. This is really important for things like a shared logging effect.

I've previously raised concerns about how we handle effects in the application. I feel like the problem has worsened considerably now that we have so many varied environments. I spent some time last week rewriting our core effects using `Run` and I find the result _much_ easier to work with. I also encountered several bugs with our ad-hoc handling of things like writing metadata to memory, the file system, and the registry. Centralizing how we handle effects like interacting with the registry repository makes for _much_ easier code to reason about.

I'm enthusiastic about being principled about our effects using `Run` because:

* `Run` is a well-tested solution for managing effects in your application
* Multiple contributors to the registry already work with `Run` in a professional setting (Colin, Jordan, and I use it at work daily and it's great.)
* Free monad effects are well-suited to writing a function once and then providing many separate interpreters, as with MTL-style effects, except that choosing a monad doesn't opt you in to all effects associated with that monad (as happens with class-based effects). We have this exact problem in the registry with the many environments we manage.

Finally, I'm personally invested in the registry as an application that others in the community can look to as an example. It's a large, complicated piece of PureScript infrastructure and I want to write it the same way I would any other real production PureScript application, and that means properly managing effects. It's one of the great strengths of the language and I want to demonstrate it. We have some examples of MTL-based systems with Real World Halogen and the other Real World X projects, but there is no large public codebase I know of that uses Run (our massive work codebase makes extensive use of it, but that's not public).

### Preview

With all of this in mind, I discussed this proposal on the registry call today and had buy-in from @MonoidMusician, @JordanMartinez, and @colinwahl to use Run to implement a proper set of effects for our codebase. My first stab at effects, which seems to work quite well but is a bit over-engineered for a first cut, can be seen trh/effect branch -- though this is incomplete given the scope of the task. Some examples:

* [A `GitHub` effect](https://github.com/purescript/registry-dev/blob/trh/effect/app/src/Registry/Effect/GitHub.purs) for making requests to GitHub repositories with Octokit
* [A `Storage` effect](https://github.com/purescript/registry-dev/blob/trh/effect/app/src/Registry/Effect/Storage.purs) for uploading, downloading, and deleting packages from an arbitrary storage backend (S3 for now)
* [An `Index` effect](https://github.com/purescript/registry-dev/blob/trh/effect/app/src/Registry/Effect/Index.purs) for reading and writing metadata and manifests
* [A `Log` effect](https://github.com/purescript/registry-dev/blob/trh/effect/app/src/Registry/Effect/Log.purs) for logging messages, whether that means pushing to a consumer over a webhook, or commenting on a GitHub issue, or writing logs to a file or log provider
* [A `Cache` effect](https://github.com/purescript/registry-dev/blob/trh/effect/app/src/Registry/Effect/Cache.purs) for storing values in a cache, whether that means in-memory, or in-memory and on the file system, or using a dedicated cache system like redis

The `Cache` effect is a bit fancy, but it's nice because the cache is now typed instead of being arbitrary JSON blobs. For example, we've previously had bugs from time to time where we write to the cache at a key with one JSON codec, but later try to read it with another codec. This is impossible with a typed cache. In action ([old code for comparison](https://github.com/purescript/registry-dev/blob/c9c96aa76cf4e68ea77e59f6cd33a2e65a19e978/app/src/Registry/Legacy/Manifest.purs#L385-L413)):
https://github.com/purescript/registry-dev/blob/694e471767fc23df29813ccef2966deb8bb9fc09/app/src/Registry/Legacy/Manifest.purs#L387-L412

### Implementation Plan

I plan to begin implementing effects with the following strategy:

1. I will implement the relevant `App.Effect.*` module along with a default handler and tests if they seem useful
2. I will then implement the same functions in the `RegistryM` module so that `RegistryM` code can use it (this minimizes churn)

In the end `RegistryM` will be a newtype over `Run` the full set of known effects, and major pieces of the codebase will remain in `RegistryM` and be largely unchanged. However, smaller functions or logically independent ones such as the `Legacy.*` modules can be implemented with only the effects they actually use, which makes them much easier to test.

### Downstream Effects

This does not affect users of the registry library because this is an application-only concern. Some of these changes may affect users of the registry application as an unstable library, but no functionality is going away and all effects have handlers that Spago can use directly to implement its own version of `RegistryM` (or it can choose to use `RegistryM` if desired).

cc: @f-f

**Comment by JordanMartinez** [comment]
Thomas already said it above, but this sounds good to me.

**Comment by f-f** [comment]
I have already expressed dissent about this months/years ago when we discussed it in multiple occasions, and my opinion is that I personally find `Run` too boilerplate-y. I am open to change my mind in the presence of a convincing implementation (as it happened with the json codecs recently); my background on this is that I'm burned out of how boilerplate-y different effect systems turned out to be when trying them out 3-4 different iterations in Spago over the years. The current one in the Haskell implementation is fairly low-code but still annoying to deal with. The new PureScript implementation uses extensible records in a Reader monad to mix and match effect handlers, and I'm happy with it so far.

This is all to say that I think your reasoning is sound, and even though I disagree on the path that shall be taken to fix it I'm fine with moving forward with this as long as we don't have to deal with the boilerplate in the Spago codebase.

**Comment by thomashoneyman** [comment]
Correct, this doesn't affect Spago whatsoever.

With regards to boilerplate, I think that no matter what system you use (run, mtl, records-of-handlers), once a reasonable chunk of functions need different interpretation then you get boilerplate. With run it's the setup of the free monad vs. the interpreter. With mtl it's having to make different monads to opt-in to a different set of instances. With records-of-handlers it's having to `ask` for functions from the environment so they can be called.

I agree with you that Run's particular brand of boilerplate is relatively greater than Spago's handlers approach, but I guess I'm just not that bothered by it. I think it gives you a lot more power to work with your effects, and the boilerplate is in the effect modules themselves.

The main thing I'm focused on is that we have structured effects and don't just throw everything into `Aff`. When we want to log something, we use an explicit logging effect. If we turn out to dislike using Run, then it's not too bad to change over to MTL and swap out the monad instead of the effects. But to switch to what Spago is doing we'd have to give up on reusing the same code with different interpretations.

For example, given some logging effect with these options:

```purs
data LogVerbosity = Quiet | Normal | Verbose

data LogLevel = Debug | Info | Warn | Error

type LogOptions = { verbosity :: LogVerbosity }
```

The Run-based one might look like this:

```purs
data Log a = Log LogLevel String a
derive instance Functor Log

type LOG r = (log :: Log | r)
_log = Proxy :: Proxy "log"

log :: forall r. String -> LogLevel -> Run (LOG + r) Unit
log level message = Run.lift _log (Log level message unit)

handleLogConsole :: forall r a. LogOptions -> Log a -> Run (EFFECT + r) a
handleLogConsole options (Log _ message next) = Run.liftEffect (Console.log message *> pure next)

handleLogGitHub :: forall r a. LogOptions -> Octokit -> IssueNumber -> Log a -> Run (AFF + r) a
handleLogGitHub options (Log _ message next) = Run.liftAff do
  GitHub.createComment octokit issue message >>= case _ of
    Left err -> Aff.throwError error
    Right _ -> pure next

myAppConsole :: Run (LOG + ()) Unit -> Aff Unit
myAppConsole = Run.runBaseAff' $ handleLogConsole { verbosity: Quiet } do 
  log "hello"

myAppGitHub :: Octokit -> IssueNumber -> Run (LOG + ()) Unit -> Aff Unit
myAppGitHub octokit issue = Run.runBaseAff' $ handleLogGitHub { verbosity: Quiet } octokit issue do
  log "hello"
```

Specifically, we reuse the same `log` function in the two `myApp*` functions, and the behavior of that `log` function is determined by what effect handler we paired it with. In one case log function runs to `Effect` and in the other it runs to `Aff`, but that's not important: what's important is that the `log` function itself only requests a handler for the `LOG` effect.

I don't see how the same can be done with the handlers-based approach without hardcoding the functions to be reused (ie. `log`) to just be implemented in `Aff`. If the handlers are hardcoded to `Aff` then they can't be used with any other effects. For example, we couldn't mix this with some `GITHUB` effect that makes requests and logs things about them.

This is my best guess:

```purs
type LogEnv m r = 
  { logOptions :: LogOptions
  , logHandlers :: LogHandlers m 
  | r 
  }

-- This gives us a reusable `log` function; to use this effect, you `MonadAsk { logHandlers :: LogHandlers ... }`
type LogHandlers m = 
  { log :: LogLevel -> String -> m Unit
  }

consoleHandlers :: forall m. MonadEffect m => LogHandlers m
consoleHandlers options =
  { log: \_ message -> do 
      Console.log message
  }

githubHandlers :: forall m. MonadAff m => Octokit -> IssueNumber -> LogHandlers m
githubHandlers octokit issue = do
  { log: \_ message -> do 
      GitHub.createComment octokit issue message >>= case _ of 
        Left err -> liftAff $ Aff.throwError error
        Right _ -> pure next
  }

log :: forall m r. MonadAff m => MonadAsk (LogEnv m + r) => String -> m Unit
log message = do
  { logOptions, logHandlers } <- ask
  logHandlers.log message

-- This is where it breaks down: what can the type of `m` for `LogEnv` possibly be except for `Aff`?
--    LogEnv Aff == { logHandlers :: { log :: LogLevel -> String -> Aff Unit }
-- How would you then mix this with other effects?
myAppConsole :: ReaderT (LogEnv Aff ()) Aff Unit -> Aff Unit
myAppConsole = runReaderT { logOptions: { verbosity: Quiet }, logHandlers: consoleHandlers } do
  log "Hello"

myAppGitHub :: Octokit -> IssueNumber -> ReaderT (LogEnv Aff ()) Aff Unit -> Aff Unit
myAppGitHub octokit issue = runReaderT { logOptions: { verbosity: Quiet }, logHandlers: githubHandlers octokit issue } do
  log "Hello"
```

None of this is a problem if you're just swapping some base implementation for a `mempty` one or something. Like if we don't have to accommodate the GitHub comment case in certain environments, then the handler-based one doesn't even need to bother about sharing an implementation. You can just always have `log` hit the console.

```purs
type LogEnv r = { logOptions :: LogOptions | r }

log :: forall m r. MonadEffect m => MonadAsk (LogEnv r) m => String -> m Unit
log message = do
  { logOptions } <- ask
  Console.log message

myApp :: ReaderT (LogEnv ()) Aff Unit -> Aff Unit
myApp = runReaderT { logOptions: { verbosity: Quiet } } do
  log "hello"
```

But this only works so long as the environment is just carrying around configuration data; it doesn't work if you want to swap out the full implementation of an effect, like is being done in the `Run` example, unless I'm missing something.

**Comment by f-f** [comment]
> but I don't see how the same can be done with the handlers-based approach, without hardcoding all the reused functions to Aff (which means they no longer can use other effects, like a GITHUB effect can't use the logger anymore)

I don't follow, both your examples are hardcoded to `Aff`?
And if you didn't want your thing to be running in hardcoded `Aff`, you could use `MonadAff`?

**Comment by thomashoneyman** [comment]
You're right that the ultimate target of the program is almost always going to be `Aff` (or, more specifically, `Effect`). The difference is in the handlers: _they_ should be able to use effects. In my handlers example above, you'll see that if we use `Aff` as the `m` for `LogEnv`, then that means the `log` function has the type `LogLevel -> String -> Aff Unit`. That means that the logging function cannot be used with other effects.

The logging function isn't a great example because it's so low-level. Let me clarify by mixing the logging effect with a cache effect to demonstrate the problem. If this problem can be avoided using the record of handlers approach used by Spago then I'm much more sympathetic to using that approach.

Let's say we had a `Cache` effect (an in-memory key-value store we use so we don't have to go to disk). When there's a cache miss we want to log that. Since we're logging we want to use our `Log` effect.

The `Run` version would be something like this:

```purs
data Cache a = Write String String a | Read String (Maybe String -> a)
derive instance Functor Cache

type CACHE r = (cache :: Cache | r)
_cache = Proxy :: Proxy "cache"

write :: forall r. String -> String -> Run (CACHE + r) Unit
write key value = Run.lift _cache (Write key value unit)

read :: forall r. String -> Run (CACHE + r) (Maybe String)
read key = Run.lift _cache (Read key identity)

-- This doesn't make use of `Aff` at all. We may have multiple ways to interpret a cache (like
-- writing to the file system, or a database, or whatever), but I'm only providing one example.
handleCachePure :: forall r a. Cache a -> Run (STATE (Map String String) + LOG + r) a
handleCachePure = case _ of
  Write key value next -> do
    Run.State.put key value
    pure next

  Read key reply -> do
    Run.State.get key >>= case _ of
      Nothing -> do
        Log.logDebug $ "Cache miss for key " <> key
        pure (reply Nothing)

      Just value ->
        pure (reply (Just value))

myAppConsole :: Run (STATE (Map String String) + CACHE + LOG + AFF ()) Unit -> Aff Unit
myAppConsole = Run.runBaseAff' $ handleLogConsole { verbosity: Quiet } $ handleCachePure $ handleState Map.empty do
  log "hello"
  write "key" "value"
  read "key" >>= case _ of
      Nothing -> log "oh no"
      Just _ -> log "oh yes"
```

What would the equivalent be if we're using handlers? This is my best guess, but please correct me if I'm getting it wrong (I've not used the approach in anger before):

```purs
type CacheEnv m r = 
  { cacheOptions :: CacheOptions
  , cacheHandlers :: CacheHandlers m 
  | r 
  }

-- I'm using a `Ref` in this example as that's more normal than using `State`, but I
-- wanted to demonstrate the pure handler in the other example
type CacheOptions r =
  { cache :: Ref (Map String String)
  | r
  }

type CacheHandlers m = 
  { write :: String -> String -> m Unit
  , read :: String -> m (Maybe String)
  }

-- An in-memory cache only, essentially the same as Run's 'cachePure'
memoryHandlers :: forall m r. MonadAsk  (CacheOptions + LogEnv m + r) => MonadEffect m => CacheHandlers m
memoryHandlers =
  { write: \key val -> do
      { cacheOptions } <- ask
      liftEffect (Ref.write key val cacheOptions.cache)

  , read: \key -> do
      { cacheOptions, logHandlers } <- ask
      liftEffect (Ref.read key cacheOptions.cache) >>= case _ of
        Nothing -> do
          logHandlers.logDebug $ "Cache miss for key " <> key
          pure Nothing
        Just value ->
          pure value
  }

write :: forall m r. MonadEffect m => MonadAsk (CacheEnv m + r) => String -> String -> m Unit
write key val = do
  { cacheHandlers } <- ask
  cacheHandlers.write key val

read :: forall m r. MonadEffect m => MonadAsk (CacheEnv m + r) => String -> m (Maybe String)
read key val = do
  { cacheHandlers } <- ask
  cacheHandlers.read key
```

The issue is that I can't actually use these effects together:

```purs
-- What is `m` here, unless it's Aff? Another stacked `ReaderT`? How do you mix effects?
myAppConsole :: ReaderT (LogEnv ?m + CacheEnv ?m + ()) Aff Unit -> Aff Unit
myAppConsole = runReaderT { logOptions: { verbosity: Quiet }, logHandlers: consoleHandlers, cacheOptions: <ref>, cacheHandlers: memoryHandlers } do
  log "hello"
  write "key" "value"
  read "key" >>= case _ of
    Nothing -> log "oh no"
    Just _ -> log "oh yes"
```

This won't work because `memoryHandlers` expects to be able to use the `log` effect via a `MonadAsk (LogEnv m r) m` instance, but if I specialize `m ~> Aff` then the instance doesn't exist. That means the `log` function becomes unusable in the cache effect _unless_ it is implemented in `Aff`, but that defeats the whole point of using effects.

The problem I can't figure out with the record-of-handlers approach is that each effect is an island: you can't implement one in terms of the other. Maybe there's a way to close the loop that I'm missing.

It's the same problem I have with the current `RegistryM`, and it's what I mean by `RegistryM` being barely better than `Aff`. Ultimately, all the effect-handling functions are just written to `Aff` so they can't use each other. For example, how do I `logDebug` the package upload? I can't!

https://github.com/purescript/registry-dev/blob/a2f872e35158274228ff0472ceb64c09634ee53b/app/src/Registry/App/RegistryM.purs#L18-L22

There is no problem if you don't overload `log`, `read`, `write`, etc. and they just work with a specific implementation (like "log to the console", "read the cache from disk") and you can use some data configuration to control bits of the implementation. But if your use case moves much beyond a single implementation that you want to toggle off for tests then I feel like the approach breaks down for the reasons I've described above. And the registry _does_ have reason to interpret effects in terms of each other and in different ways -- such as logging to a file on the server vs. logging by creating comments on a GitHub issue.

**Comment by thomashoneyman** [comment]
I've spent some more time thinking about this issue, and with some advice from @natefaubion I think I've hit on a solution that will accomplish the following goals:

1. Effects and their interpretation are separate (ie. not written in `Aff` directly).
2. Effects can be interpreted in terms of each other (ie. a `Cache` effect can rely on a `Log` effect without requiring a specific implementation).
3. Effects are relatively low-boilerplate (in terms of implementing a new effect, implementing its interpreters, using those interpreters to run to `Aff`, and writing functions that rely on the effects).
4. Functions implemented using effects can be interpreted in multiple environments (ie. they are not fixed to a particular interpretation)

I'd like to describe and demonstrate the approach, and then suggest how I can go forward with migrating the codebase to use it. As always, I'd love to hear how you feel about this @f-f @monoidmusician @colinwahl

## Approach

In short, I think we should use a take on MTL with the following properties:

1. Effects are implemented as Monad* classes. Members of those classes are the reusable functions (`logDebug`, `readCache`, etc.).
2. The effect module also supplies interpreters for different environments, the way you would with Run (`handleLogConsole`, `handleLogFileSystem`), etc.
3. Effects are chosen for particular environments by implementing a `EnvironmentM` monad that provides instances for the effects it needs by mixing and matching handlers.
4. The monad supplying instances for the various effects is also responsible for supplying configuration data used by the handlers via some `Env` supplied via `ReaderT`, essentially the same as is done in record-of-handlers

This keeps us _essentially_ using record-of-handlers, except we rely on type classes for the function overloading (which is the point of type classes in the first place!). I've moved away from `Run` since it is admittedly more complicated, less-known, and not as well supported by language features. Even though I like it a lot!

The most direct comparison to what I am suggesting is MTL-style `Monad*` classes, which gives us the ability to separate effects and their interpretation:

```purs
-- Effect.Log
data LogLevel = Debug | Warn | Error

class MonadLog m where
  log :: LogLevel -> String -> m Unit

logDebug :: forall m. MonadLog m => String -> m Unit
logDebug = log Debug

-- Effect.Cache
class MonadCache m where
  put :: String -> String -> m Unit
  get :: String -> m (Maybe String)
```

But, since we are going to be writing instances for several different environments (ie. `TestM`, `ServerM`, `GitHubM`, `LocalM`), we take a note from `Run` and implement the effect handlers with the effect so they can be easily used to implement the monads later on. This is also where we can interpret effects in terms of each other:

```purs
-- Effect.Log

-- Interpret `log` in terms of MonadEffect
logConsole :: forall m. MonadEffect m => String -> m Unit
logConsole = Console.log

-- Interpret `log` in terms of MonadAff, requiring a logfile from the environment
-- (but without determining the shape of that environment)
logFileSystem :: forall m. MonadAff m => FilePath -> String -> m Unit
logFileSystem logfile message = do
  logConsole message
  liftAff $ FS.Aff.appendTextFile logfile message
  
-- Effect.Cache

-- Interpret `put` in terms of MonadLog and MonadEffect
putMemory :: forall m. MonadLog m => MonadEffect m => Ref (Map String String) -> String -> String -> m Unit
putMemory ref key value = do
  logDebug $ "Putting key" <> key
  liftEffect $ Ref.modify_ (Map.insert key value) ref
```

And, since those instances need access to configuration data so it can be passed to the handlers themselves, we'll use an environment of configuration the same as the record-of-handlers does:

```purs
-- Effect.RegistryM

type RegistryEnv = { logfile :: FilePath, cache :: Ref (Map String String) }

newtype RegistryM a = RegistryM (ReaderT RegistryEnv Aff a)

instance MonadLog RegistryM where
  log level message =
    -- we reuse the handler and provide args from the environment.
    ask >>= \{ logfile } -> logFileSystem logfile level message

  -- alternately handlers can ask for their environment with MonadAsk,
  -- in which case the implementation is just:
  log = logFileSystem
  

instance MonadCache RegistryM where
  put key value = 
    ask >>= \{ cache } -> putMemory cache key value
  
-- Test.TestM

-- The environment is not going to be the same for all implementations, because
-- some will require information others don't.
type TestEnv = { }

newtype TestM a = TestM (ReaderT TestEnv Aff a)

instance MonadLog TestM where
  log = logConsole

-- Maybe we don't test functions that use the Cache effect, so we
-- don't have to implement it. For example, we can omit the GitHub
-- effect in tests, it's not needed. Or we can omit the username, issue,
-- etc. fields from the environment in the ServerM monad because it's
-- not triggered from a GitHub issue.
```

Finally, we can either write functions that request these effects as-needed, or we can make a class that subsumes the various common effects we need and thereby request all effects at once, even if we aren't using them.

The trade-off is that the person running the function may have to supply unused effects, but the person writing the function gets to save on boilerplate. For example:

```purs
class (MonadLog m, MonadCache m, MonadAff m) <= MonadRegistry m

doStuff :: forall m. MonadRegistry m => m Unit
doStuff = put "hey" "there" *> logDebug "what" *> pure unit\

-- compare to:
doStuff :: forall m. MonadLog m => MonadCache m => MonadAff m => m Unit
doStuff = ...

-- So long as the relevant monad has implemented the effects requested
-- by MonadRegistry it's trivial to add:
instance MonadRegistry RegistryM
```

I hope this solution is palatable for how we manage effects in this application, and isn't too hard for new contributors to the registry to grok. The boilerplate is contained in the effect modules and doesn't propagate outwards throughout the codebase (is `MonadRegistry m => m Unit` much worse than `RegistryM`?

## Next Steps

It's tempting to move over all effects at once, because we can get the whole thing over with in one go instead of piecemeal reworking functions again and again as subsequent effects are introduced. However, this would lead to thousands of lines of code to review, and any debate over the effects would lead to a ton of churn.

So: my plan is to begin with the `Log` effect and replace our use of `Console.log` anywhere we have `RegistryM` code today. To do that, I also have to replace `RegistryM` with a `MonadRegistry m` constraint so that the same code can be used with e.g. `RegistryM` and `TestM`. Then we can introduce other effects one-by-one (`Cache`, `Storage`, `GitHub`, `Index`, etc.).

However, there are downsides to this. The migration will, at first, look like it's just adding noise: we'll still have our `Aff` handlers in the environment and will _also_ have separate machinery to accommodate the new `Log` effect. The code is going to be noisy until we can remove the `Aff` handlers and just use effects, at which point it will be nice and tidy.

For example, take this function:

```purs
fetchRegistryIndex :: RegistryM Unit
fetchRegistryIndex = do
  registryIndexPath <- asks _.registryIndex
  Console.log "Fetching the most recent registry index..."
  liftAff $ fetchRepo Constants.packageIndex registryIndexPath
```

In the future, using a `GitHub` effect, it would look more like this:

```purs
fetchRegistryIndex :: forall m. MonadRegistry m => m Unit
fetchRegistryIndex = do
  Log.debug "Fetching the most recent registry index..."
  GitHub.fetchRegistryIndex
```

But during the transition it will look awful. We still have to supply file paths for the `Aff`-based fetching, _and_ the `MonadRegistry` constraint to support the `Log` effect:

```purs
fetchRegistryIndex :: forall m r. MonadRegistry m => MonadAsk (GitHubEnv r) m => m Unit
fetchRegistryIndex = do
  registryIndexPath <- asks _.registryIndex
  Log.debug "Fetching the most recent registry index..."
  fetchRepo Constants.packageIndex registryIndexPath
```

I just want to note that it doesn't mean the approach sucks, it means the _transition_ sucks :).

**Comment by f-f** [comment]
Thanks for taking another look at this @thomashoneyman! I would not personally mind having a single big PR that transitions us to the new effect system, so that we can skip the transition issues.

**Comment by thomashoneyman** [comment]
How do you feel about that, @colinwahl and @MonoidMusician?

A word of warning: it’s not possible to introduce the effects without making pervasive changes in the codebase, as they’re so low level.

For example, I’d like the cache effect to perform logging, and the GitHub requests rely on the cache, and therefore they must be lifted from Aff into MonadRegistry and moved into Registry.App. (I can keep the basic octokit bindings in Foreign, as well as the basic request FFI function.)

I am going to do my best to not change the behavior of any of the functions in the application except where I’ve already noticed bugs, but it will be somewhat difficult as a reviewer to verify that. Luckily we have lots of tests and the scripts can be run in dry-run mode, and I’ll add more tests. 

If y’all are down to trust me to rip the bandaid off and get this over with then I can certainly do it — and it’ll be much faster and less tedious than reviewing one-by-one. But you will have less of an opportunity to deep-dive into and provide feedback on each iterative change.

I will go ahead with the all-in-one approach unless one of you prefer I don’t, and say so in the next couple of days. Thanks!

**Comment by colinwahl** [comment]
@thomashoneyman Thanks for going over all of our options.

I'm with @f-f in thinking we should just go ahead with it all at once - I can commit time in the coming weeks to review a larger PR, and would be open to pairing to go over more tricky bits.

**Comment by thomashoneyman** [comment]
Ok, great!

Of course, if anyone _prefers_ Run I can return to that. But otherwise I'll use the MTL-inspired version.
