### ISSUE TITLE
Hash mismatches for a large number of packages

### ISSUE THREAD

**Issue by considerate** [purescript/registry-dev#585]
The `hash`es in the `published` information do not seem to correspond to the hashes of the tarballs on the storage backend.

This build log is when trying to test all packages in the 8.6.0 package set:

[build.log](https://github.com/purescript/registry-dev/files/10473870/build.log)

I have tested to download and extract the contents of individual packages and they contain the expected information but they hash to what is listed as `got:` in the log, not the specified hashed in the `published` information.

**Comment by considerate** [comment]
I looked at some of the packages, and it seems like the hash has changed on `main` compared to a version from a couple of weeks ago.

Bumping the version of the registry seems to have solved the issue. It was quite unexpected behavior that the hashes aren't consistent over time.

Should I expect the hashes for already published packages to change in the future as well? Was this just a one time thing and the tarballs can be assumed to be immutable for a specific version in the future?

**Comment by MonoidMusician** [comment]
Yes, we had to reimport a bunch of packages due to changes in the legacy dependency logic: https://github.com/purescript/registry-dev/pull/580

This should stabilize soon, but we will likely do a mass reimport of packages before we are out of the alpha stage, so more packages may change then.

**Comment by considerate** [comment]
@MonoidMusician Thank you for the quick reply.

That's very reassuring to hear. Having to bump the registry version once or twice doesn't seem like it's going to be a big issue.

Do you have a rough estimate of when the alpha stage is ending?

**Comment by MonoidMusician** [comment]
I don't know, maybe a couple months. I think setting up a registry server (so requests don't have to go through PR workflows) and some more polish on the new spago are the main tasks left. Speaking of which, I just remembered I need to make a PR to spago …

**Comment by considerate** [comment]
Thank you! That sounds good to me.

I'm closing this issue because after bumping the registry version I was now able to build all packages in the 8.6.0 package set that I used for testing.
