### ISSUE TITLE
Is the registry down?

### ISSUE THREAD

**Issue by deemp** [purescript/registry-dev#637]
Hi, @thomashoneyman, @f-f ! I can't build a package using `purifix` as a build gets stuck at 

```
bifunctors-6.0.0.tar.gz> trying https://packages.registry.purescript.org/bifunctors/6.0.0.tar.gz
bifunctors-6.0.0.tar.gz> curl: (28) Failed to connect to packages.registry.purescript.org port 443 after 261780 ms: Couldn't connect to server
bifunctors-6.0.0.tar.gz> Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
```

These lines are a part of `nix-output-monitor` output.

Is this a wrong package link?
Or, is the registry down?

It would be nice to see an OpenAPI3 spec at `https://packages.registry.purescript.org`

**Comment by thomashoneyman** [comment]
That looks correct to me, and I’m able to download from it. Perhaps it was a hiccup in connectivity? The registry storage has been serving downloads through the day today as far as I can tell.

**Comment by deemp** [comment]
Thank you. I should've tried with VPN :facepalm:
