### ISSUE TITLE
Replace Affjax with Fetch

### ISSUE THREAD

**Issue by thomashoneyman** [purescript/registry-dev#643]
The [fetch](https://github.com/rowtype-yoga/purescript-fetch) library by @sigma-andex and @i-am-the-slime takes advantage of Node's support of the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) since Node 18. It's a little more comfortable for sending buffer data in Node (see #642), and it has no JS library dependencies — Affjax relies on the elderly `xhr2` library.

This issue tracks replacing our use of Affjax with Fetch. Fortunately we don't make many requests; they're all in the following modules:

* [App.Prelude](https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/src/App/Prelude.purs#L159), used in the `withRetryRequest` helper
* [App.Effect.Source](https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/src/App/Effect/Source.purs#L133-L137), used to download tarballs from GitHub into a buffer
* [App.Effect.Storage](https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/src/App/Effect/Storage.purs#L242-L247), used to download tarballs from the registry backend into a buffer
* [App.Effect.Pursuit](https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/src/App/Effect/Pursuit.purs#L65-L78), used to POST json data to Pursuit to upload packages

We'll also want to drop the dependencies in `spago.yaml`:
https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/spago.yaml#L10-L11

As well as drop the `xhr2` dependency from `package.json`:
https://github.com/purescript/registry-dev/blob/8177cd30d7b7cf3379b8b728564def0ed438298c/app/package.json#L10

**Comment by CharlesTaylor7** [comment]
I am volunteering to work on this: https://github.com/purescript/registry-dev/issues/642#issuecomment-1690407659
